### PR TITLE
Support "list" pipeline argument

### PR DESCRIPTION
**Pull request by svlandeg**
## Description
The `pipeline` argument for `init config` should be a comma-seperated list like `-p "tagger, textcat"`. However, I think it is likely for people to try to write `-p "[textcat]"` (as in the config). So we may as well support this, because it gives an ugly error downstream otherwise. With this edit, we even support people writing something like `-p "["tagger", "textcat"]"`

### Types of change
enhancement

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
This is a good idea and I think we should maybe have a more general-purpose helper for it? I could think of a few other places to use it (everything that takes comma-separated values).

**Comment by svlandeg** [comment]
Yea, makes sense, in `cli/_util.py` ?

**Comment by ines** [comment]
Yes, sounds good 👍

**Comment by svlandeg** [comment]
> 
> **Edit:** Also, now that I think about it, maybe we do need more sophisticated logic here if we want to support the list syntax properly? For example, we need to strip out the quotes and handle both single and double quotes etc.?

I extended the function and wrote two unit tests, it should cover quite a lot of cases now :-)

**Comment by ines** [comment]
Okay cool, this looks solid 😅💪

**Pull request merged**
