### PR TITLE
pymorphy issues #11620, #11626, #11625:

### PR DESCRIPTION
**Pull request by DSLituiev**
Fix for multiple issues pertaining to `pymorphy` (now @`develop` branch)

## Description
- fix for #11620: pymorphy2_lookup
- fix for #11626: handle multiple forms pointing to the same normal form + handling empty POS tag
- fix for #11625: matching DET that are labelled as PRON by pymorphy
- test for pymorhpy in `spacy/tests/pipeline/test_pymorphy_lemmatizer.py` 
- refactor a common `pymorphy` lemmatizer class into a separate file `spacy/pipeline/pymorphy_lemmatizer.py` (alongside `lemmatizer.py` and `edit_tree_lemmatizer.py`)

### Types of change
bug fix and enhancements

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by DSLituiev** [comment]
the test is failing because of missing `pymorph2` installation

**Comment by adrianeboyd** [comment]
Sorry for the confusion, we've now switched back to `master` as the branch for v3.5. I'll update the PR in a second, which hopefully won't cause too many problems with the history. Even if it does, we can clean it up on our end before it's merged.

We'd prefer that modules with optional language-specific dependencies are all in `spacy.lang` rather than `spacy.pipeline`, even if they are pipeline components.

There's not really a good general place to put this, but you can move `pymorphy_lemmatizer.py` to `spacy.ru` or `spacy.uk`.

The optional dependencies require special handling in the test suite. Usually we manage this through fixtures like `ru_tokenizer` and `ru_lemmatizer`, but if there are general tests outside of `ru` or `uk` you can also use `importorskip` as a test marker.

**Comment by DSLituiev** [comment]
Thank you. Would you like me to move `pymorphy_lemmatizer.py` or would you be able to do that on your end with the rest of clean-up work?

**Comment by adrianeboyd** [comment]
If you'd like to hand the PR over at this point, that's fine and I can continue working on it in a new branch.

If you'd like to continue working on it, I can provide direct review comments, or possibly push directly to this branch for minor fixes if that's okay with you.

**Comment by adrianeboyd** [comment]
PR continued in #11811.

**Pull request closed without merging**
