### PR TITLE
Refactor Chinese tokenizer configuration

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Refactor `ChineseTokenizer` configuration so that it uses a single `segmenter` setting to choose between character segmentation, jieba, and pkuseg.

* replace `use_jieba`, `use_pkuseg`, `require_pkuseg` with the setting `segmenter` with the supported values: `char`, `jieba`, `pkuseg`
* make the default segmenter plain character segmentation `char` (no additional libraries required by default)

### Types of change

Enhancement.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
This looks much better! The docs change is quite nice.

@ines Do we have to update the examples in the Chinese course for this?

**Comment by adrianeboyd** [comment]
I'm hoping to standardize this a bit across languages, so any API changes/suggestions are welcome at this point.

I tried using an enum instead just a tuple of strings of supported segmenters, but it seemed like too much hassle.

**Comment by ines** [comment]
@honnibal At the moment, the examples are still all in English. And I don't think this would change much, because it's not like the actual output of the `pkuseg` tokenization will be different, right?

**Comment by honnibal** [comment]
@ines Okay, great. I just wasn't sure whether we had usage examples that loaded the Chinese model.

I can see why the enum was tempting here, unfortunately I don't think I've ever found it helpful. So I'll go ahead and merge this.

**Pull request merged**
