### PR TITLE
Hindi: Adds tests for lexical attributes (norm and like_num)

### PR DESCRIPTION
**Pull request by rahul1990gupta**
This PR 
- adds some tests for lexical attribute function like_num 
- adds some tests for lexical attribute function norm 
- In norm function, it replaces `break` by `continue` which allows processing smaller words which it was not processing earlier. Added tests to ensure that. 
- It expands Hindi Number vocabulary. 
- It adds vocabulary to recognize ordinal numbers in Hindi as mentioned in the issue https://github.com/explosion/spaCy/issues/5827
 
### Types of change

- It fixes bugs in like_num and norm functions 
- It adds tests for both function 
- Expands like_num vocabulary. Not sure, if that qualifies as an enhancement.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
@rahul1990gupta : I converted this to draft for now, as I saw there were some review comments on the related (closed) PR https://github.com/explosion/spaCy/pull/5828 - can you have a look at those?

(I'm not sure what the difference between the two PRs is?)

**Comment by rahul1990gupta** [comment]
Thanks @svlandeg for the quick update.
The other PR was created from master branch of my fork, which was coming in the way of workflow. So, I made a feature branch with the same diff to create a new PR. 

I have addressed the comments to the satisfaction of the reviewer. This PR is ready to be reviewed.

**Comment by rahul1990gupta** [comment]
@adrianeboyd @honnibal 

Can I get a review on this as well, please ?

**Comment by adrianeboyd** [comment]
Sorry we didn't get back to this sooner! I think everything looks good and we will get this merged.

**Pull request merged**
