### PR TITLE
Docs: Addition of an Issue Template

### PR DESCRIPTION
**Pull request by sambozek**
###

## Description

Following #584 felt addition of an issue template would be helpful as well.

## Motivation and Context

Makes the process of reporting a bug more transparent. Focus on providing reproducible steps allows for collaborators to quickly verify the issue. 

## How Has This Been Tested?

This is the addition of another markdown file in the .github/ directory. Tested on master branch of my spaCy fork to see if issue template works. Tested on chrome browser on github.

## Types of changes

- [ ] Bug fix (non-breaking change fixing an issue)
- [ ] New feature (non-breaking change adding functionality to spaCy)
- [ ] Breaking change (fix or feature causing change to spaCy's existing functionality)
- [x ] Documentation (Addition to documentation of spaCy)

## Checklist:

- [ x] My code follows spaCy's code style.
- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by honnibal** [comment]
I'm worried that this is a bit heavyweight. I'd rather keep the volume of reports up, and the difficulty of reporting low. Is this what everyone else is doing?

**Comment by ines** [comment]
Thanks for the work, much appreciated!

@honnibal I see your point!

Maybe we could trim this a little and mostly add comments at the top to remind people to attach all required info to make it easy to reproduce a bug / show detailed examples of their problem. I like the environment questions though, I think they should stay.

It could also be nice to mention the StackOverflow tag in case what people want to report is more of a general usage or Python-related question (like "Why is my code not working?" etc.)

**Comment by sambozek** [comment]
@honnibal @ines thanks for your input! Will tighten it up, focus on single top comment asking for detail and keep environment section. Reference to stackoverflow tag is definitely a good addition.

**Comment by honnibal** [comment]
Thanks!

**Pull request merged**
