### PR TITLE
Make Span.char_span optional args keyword-only

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Make `Span.char_span` optional args keyword-only

### Types of change

?

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
There were inconsistencies in the names `start` vs. `start_idx`. Since `Doc.char_span` also uses `start_idx`, I updated the docs here in addition.

Actually, we'd need to do this in `Doc`, too, wait a sec.

**Comment by svlandeg** [comment]
> Actually, I'm not sure we want to do this. I think many people are using `Doc.char_span(3, 15, "LABEL").

Hmm, true, though as soon as you start getting into the KB ID stuff etc, it really is better and more safe to use kwd-args. So maybe include `label` in the non-kwd-only-args?

**Comment by adrianeboyd** [comment]
I'm still not sure in this particular case that it is worth being this breaking. There was even a case in `Doc`.

**Comment by svlandeg** [comment]
It feels pretty arbitrary to me to have `kb_id` as the fourth positional argument, and by introducing the kwd-args in v4 we'd allow ourself to make changes to the list without being breaking going forward, as well enforcing downstream code to be more specific and thus less error-prone, so I personally think that's a good trade-off.

**Pull request merged**
