### PR TITLE
Set version to 3.7.5

### PR DESCRIPTION
**Pull request by svlandeg**
## Description
Set version to 3.7.5

### Types of change
maintenance

## Checklist
- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
@explosion-bot please test_slow

**Comment by svlandeg** [comment]
@explosion-bot please test_gpu

**Comment by svlandeg** [comment]
Slow tests are green, GPU tests couldn't run because there's no agent available. I'll go ahead and merge this.

**Comment by narayanacharya6** [comment]
Can this version be published to pypi please? :)

**Comment by aymenkrifa** [comment]
Will there be a release in the upcoming days? @svlandeg

**Comment by svlandeg** [comment]
Hi! We ran into an unexpected issue when building the wheels for this, and we're working on it.

**Comment by svlandeg** [comment]
Now released to PyPI: https://pypi.org/project/spacy/3.7.5/

**Pull request merged**
