### PR TITLE
Support list values and INTERSECTS in Matcher

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Support list values as token attributes for set operators, not just as
pattern values.

* Add `INTERSECTS` operator.

* Fix incorrect `ISSUBSET` and `ISSUPERSET` in schema and docs.

### Types of change

Enhancement, minor docs/bug fix.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
`IS_INTERSECT` is probably not the best name. Maybe just `INTERSECTS`?

**Comment by honnibal** [comment]
I think `INTERSECTS` is a good name, yeah. Is this mergeable?

**Comment by adrianeboyd** [comment]
I think so, yes?

**Comment by svlandeg** [comment]
Looks good to me!

**Pull request merged**
