### PR TITLE
Add greCy to Universe

### PR DESCRIPTION
**Pull request by jmyerston**
## Description

Add greCy (ancient Greek models to spaCy universe)
### Types of change

Project description with links. 
## Checklist

- [X ] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the PR! Since this is a draft, is there something else you wanted to add before it gets merged?

The current contents look OK, except that the Github value should be just of the format `jmyerston/grecy`, and not the whole Github URL - that's why the tests are failing.

**Comment by jmyerston** [comment]
Thanks for the feedback! I fixed the GitHub value. I will extend the description in the future as the project develops. Next release should contain improved sentence segmentation, and after that I will add the NER pipeline.

**Comment by jmyerston** [comment]
I think you can merge it if you agree.

**Comment by polm** [comment]
Looks good, thanks!

**Comment by adrianeboyd** [comment]
Just a note: usually universe updates like this are pushed to the website as soon as they're merged, but we're working on some website upgrades in the background so this will be delayed a bit.

**Pull request merged**
