### PR TITLE
Fix v4 branch to build against Thinc v9

### PR DESCRIPTION
**Pull request by danieldk**
## Description

This PR backports some changes from the parser refactor to make the `v4` branch compile against the Thinc `v9` branch again. The backports are not cherry picks, since too many things changed between the parser versions to make this a clean cherry pick. Changes:

* Backport https://github.com/explosion/spaCy/pull/11317
* Backport https://github.com/explosion/spaCy/pull/11292
* Change `SequenceCategoricalCrossentropy` to `LegacySequenceCategoricalCrossentropy`. Eventually, we want to move to the new losses, but the goal of this PR is to make spaCy v4 work again.

This PR also requires https://github.com/explosion/thinc/pull/809.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
@danieldk : we should run the GPU and slow tests here to make sure nothing broke (preferably after `thinc-apple-ops` is also released)

**Review by svlandeg — COMMENTED** [review]
Thanks for this Daniel 🙏 

This all looks sensible to me - though TBH I haven't gone in and reviewed every single line, assuming that most of this is copy/paste from previous work anyway, right?

> Change SequenceCategoricalCrossentropy to LegacySequenceCategoricalCrossentropy. Eventually, we want to move to the new losses, but the goal of this PR is to make spaCy v4 work again.

Did you create a task on our internal board for v4 to ensure we don't forget this?

**Comment by danieldk** [comment]
> This all looks sensible to me - though TBH I haven't gone in and reviewed every single line, assuming that most of this is copy/paste from previous work anyway, right?

Yeah, they are only backports and some renaming for the losses.

> Did you create a task on our internal board for v4 to ensure we don't forget this?

Done.

**Comment by danieldk** [comment]
@explosion-bot please test_gpu

**Comment by danieldk** [comment]
@explosion-bot please test_slow

**Review by svlandeg — APPROVED** [review]
Nice work! Good to merge by me :-)

**Pull request merged**
