### PR TITLE
♻ Refactor CLI setup for completion

### PR DESCRIPTION
**Pull request by tiangolo**
### Types of change

This PR does the following:

* Pin Typer to a version range safe from breaking changes (there could be breaking changes between `>=0.3.0` and `>=0.4.0`).
* Add `shellingham` as a dependency, a small library used by Typer to detect the current shell and be able to install completion automatically with:

```console
$ spacy --install-completion
```

Without `shellingham` it would have to be:

```console
$ spacy --install-completion zsh

// or

$ spacy --install-completion bash

// or

$ spacy --install-completion fish

// etc.
```
* Update the way the standalone `spacy` command is created, from an integrated shell script to a pure Python "entrypoint" in setuptools:
    * This fixes shell completion because with the current shell script the actual command called ends up being `python -m spacy some-args` instead of `spacy some-args`. And shell completion systems depend on that name of the command (otherwise, it triggers completion for `python`).

Here's how completion looks like afterwards:

[asciicast](https://asciinema.org/a/GTlCdFuDLI0VnSoqotwqIH3NK)

## Checklist

- [x] I have submitted the spaCy Contributor Agreement. ...I think so? I actually don't know :thinking: 
- [x] I ran the tests, and all new and existing tests passed. (Didn't change any internals).
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Wowwww, this looks cool 🤩

> Add shellingham as a dependency, a small library used by Typer to detect the current shell and be able to install completion automatically with:

I think we'd be a bit reluctant to adopt a new third-party dependency in spaCy just for this feature (it's convenient, but it probably doesn't justify the extra dependency). @honnibal, what do you think?

**Comment by tiangolo** [comment]
Sure! Should I remove it right away?

**Comment by honnibal** [comment]
Yeah I think people can just write their shell? The detection is one more thing to go wrong, too

**Comment by tiangolo** [comment]
Perfect, done! :heavy_check_mark:

**Pull request merged**
