### PR TITLE
Add Entity Linking to menu on website

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Add Entity Linking to menu on website

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by AroundtheGlobe** [comment]
The "Entity Linking" menu item doesn't change color when you click on it or read that part of the website.

**Comment by adrianeboyd** [comment]
Hmm, it seems okay for me. I'm not sure what might be going on.

**Comment by AroundtheGlobe** [comment]
Go to https://spacy.io/usage/linguistic-features#entity-linking now scroll up until "Named Entities" changes color, next scroll down again. You should see that Entity Linking is skipped and Tokenization is picked. Yesterday it didn't seem to work at all for whatever reason. I am on FireFox 70.0.1

**Comment by adrianeboyd** [comment]
I think this is just a weird quirk in the section highlighting behavior when the section is less than one screen length long. I can see the behavior you're describing, but if you make your window shorter, it does get highlighted correctly.

**Pull request merged**
