### PR TITLE
Korean support

### PR DESCRIPTION
**Pull request by cedar101**
Add Korean(ko) tokenizer(morphological analyzer) support to spaCy.

## Description

It currently requires [mecab-ko](https://bitbucket.org/eunjeon/mecab-ko/src/master/README.md),     [mecab-ko-dic](https://bitbucket.org/eunjeon/mecab-ko-dic), and [natto-py](https://natto-py.readthedocs.io).

### Types of change

*  **New feature** (non-breaking change adding functionality to spaCy)

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks, this looks great!

One small thing: is there a reason to add the `Pipfile`? Which tool does this relate to?

**Comment by ines** [comment]
Resolved the conflict, so this should be ready to merge once the tests go green 👍

**Comment by yspaik** [comment]
Is the spacy Korean included in the current stable version?

**Comment by BarnabasSzabolcs** [comment]
Can you please tell me what is the name of the trained Korean model that I can load with spacy.load()?

@tylee33 I think you may be interested, too, because I read you used to train a Korean model for Spacy.

Thanks,
Barney

**Comment by polm** [comment]
There is no Korean model yet. This PR added support for tokenization, which we consider alpha support. To use it you need a working mecab-ko install and you need to `pip install spacy[ko]`. You can check language support [here](https://spacy.io/usage/models#languages), and install instructions in the [install widget](https://spacy.io/usage).

**Pull request merged**
