### PR TITLE
Added eMFDscore to universe.json

### PR DESCRIPTION
**Pull request by fhopp**
## Description
Addition of eMFDscore library to the spacy universe. No edits to main codebase or documentation.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the submission! The project looks good, but could you include a bit more detail in the `description` field? Something like the first paragraph of your README would be great.

**Comment by fhopp** [comment]
Thanks for the note! I added the longer description. Hope to see this project on the universe soon. Thank you!

**Review by polm — CHANGES_REQUESTED** [review]
"build" should be "built". Tried to fix it but looks like I can't push to this branch. 

Other than that looks good!

**Comment by fhopp** [comment]
Thanks for catching that. It is now corrected.

**Review by polm — APPROVED** [review]
Looks good!

**Pull request merged**
