### PR TITLE
Added model command to create models from raw data

### PR DESCRIPTION
**Pull request by GreenRiverRUS**
I'm not sure that this command should be added, but since I have already written it for myself, why not share it :smile:

## Description
I've merged v1.x `model` cli command with v2.x `vocab` command into a new one, which helps to create models from raw data: words counts, brown clusters and vectors.
The command requires the following parameters:
- `lang`: model language
- `output_dir`: model output directory to store to
- `freqs_loc`: path to word counts file, should be in format, which described [here](https://spacy.io/usage/adding-languages#training)
- `clusters_loc`: [optional] location of Brown clusters data in format produced by [this](https://github.com/percyliang/brown-cluster) script
- `vectors_loc`: [optional] location of [word vectors](https://spacy.io/usage/adding-languages#word-vectors) file in GenSim text format (created by default)
- `prune_vectors`: [optional] number of vectors to prune to

### Types of change
- [x] New feature (non-breaking change adding functionality to spaCy)

## Checklist

- [x] I have submitted the spaCy Contributor Agreement (in first PR)
- [x] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Thanks, this is cool! 👍 

One thing I've been thinking of: In spaCy v1.x, we never really liked the name `model` that we came up with for this command, because it's so vague... so maybe you have an idea for a better name? It'd definitely be great to bring this functionality back in spaCy v2.x.

**Comment by GreenRiverRUS** [comment]
@ines
Maybe `init` as `git init`, but it isn't speaking for itself :thinking: . I'm not good at naming, unfortunately.

**Comment by ines** [comment]
Hmm, maybe `init-model`, `model-data` or `lang-model`? Just `spacy init` might be a bit weird, because it sounds like you're... initialising spaCy or something. I'll think about this and see what @honnibal thinks!

**Comment by ines** [comment]
Merging this and will make a few more edits afterwards, including the name change 👍

**Pull request merged**
