### PR TITLE
Add tokenizer exceptions for French

### PR DESCRIPTION
**Pull request by raphael0202**
Add tokenizer exceptions in French

## Description
Add tokenizer exceptions in French, using a list of tokens (saved in a file) and a regex-based matcher (using the BaseDefault.token_match attribute). See issue #783 for the rational behind the approach chosen.

Some tokenizer exceptions could not be spotted however - essentially specific tokenization in hyphen-delimited expression such as `a-t-elle` that should be tokenized as `['a', '-t', '-elle']`- so just the most common of these exceptions were manually added.

## Types of changes
- [x] **Bug fix** (non-breaking change fixing an issue)
- [ ] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:
- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ines** [comment]
Thanks, this looks great – and seems like this was really a good use case for the new `token_match`.

Before I merge, could you have a quick look at that conflict? I'm not entirely sure what it's complaining about, it might just be related to some of the reordering / reformatting.

**Comment by raphael0202** [comment]
The conflict was due to recent additions to the list of tokenizer exceptions, it's now resolved.

**Comment by ines** [comment]
Ok perfect, merging now! (Ignore the Travis fails btw, this is still an issue with our build server.)

**Comment by raphael0202** [comment]
Great, thanks!

**Comment by ines** [comment]
@raphael0202 Sorry, I had to temporarily revert this commit because it kept hitting the `sorry, but this version only supports 100 named groups` Python error. But making all groups non-capturing (e.g. `di(?:sney)?`) fixed the problem 👍

The new changes are now on master (see f08e180a47e71d2af60df1f53de1c7877a974b51). All tests pass, so fingers crossed for the build.

**Comment by raphael0202** [comment]
@ines Oh ok, it's weird because all the tests passed. How did it occur? Thanks for making the fix

**Comment by ines** [comment]
Okay, so after digging around for a bit, I think I found the explanation: Are you using Python 3 by any chance? Apparently, the 100 groups limit in Python 2 has been removed (or at least, increased) in Python 3. So that might be why I hit this error and you didn't.

Here's what I got in Python 2 when running the tests (or doing anything with spaCy, since the groups limit prevented the tokenizer exceptions from being compiled):

```bash
  File "spacy/fr/tokenizer_exceptions.py", line 215, in <module>
    TOKEN_MATCH = re.compile('|'.join('({})'.format(m) for m in REGULAR_EXP), re.IGNORECASE).match
  File "spacy/.~env/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "spacy/.~env/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "spacy/.~env/lib/python2.7/sre_compile.py", line 583, in compile
    "sorry, but this version only supports 100 named groups"
AssertionError: sorry, but this version only supports 100 named groups
``` 

It's good that this came up, though. I'll try to remember to add a note about the group limit in Python 2 when we add the `token_match` docs.

The [Travis builds](https://travis-ci.org/explosion/spaCy/builds/200020992) for Python 3 still failed, but for a different reason: `test_issue768.py` is importing the `TOKENIZER_EXCEPTIONS` from `fr/language_data.py` – but they don't actually exist there anymore. So I fixed that as well in the above commit.

It's maybe not ideal to add this one extra step (`tokenizer_exceptions` -> `language_data` -> `__init__`),  but for now, it keeps it consistent with the other languages. The original idea here was that all language-specific data is bundled in`[language]/language_data.py`, so it can always be imported predictably from there.

**Comment by raphael0202** [comment]
Sorry for my late answer.
Yes I'm using Python3, and I haven't launched the tests on Python2. And I only launched the default 'fast' tests.

**Pull request merged**
