### PR TITLE
Add vector deduplication

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Add `Vocab.deduplicate_vectors()`
* Always run deduplication in `spacy init vectors`
* Clean up a few vector-related error messages and docs examples

### Types of change

Enhancement.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
@explosion-bot please test_gpu

**Comment by adrianeboyd** [comment]
I am not putting in a lot of effort to make this efficient. It would typically run once on CPU with `spacy init vectors`.

**Comment by ryndaniels** [comment]
@explosion-bot please test_gpu

**Comment by ryndaniels** [comment]
This is a test comment to see what explosion-bot does.

**Comment by adrianeboyd** [comment]
@explosion-bot please test_gpu

**Review by svlandeg — APPROVED** [review]
Looks good! 🎉

**Comment by adrianeboyd** [comment]
I ran a full suite of trained pipeline builds with no issues with this PR (although it only affects English in the end). It reduces the size of `en_core_web_lg` by 350MB.

**Comment by svlandeg** [comment]
Nice!

**Pull request merged**
