### PR TITLE
Lemmatization (lookup) and some corrections in the french language

### PR DESCRIPTION
**Pull request by Gregory-Howard**
## Description
Initial lemmatization feature following : #846
I would like to change the name of spacy/lemmatizerlookup.py,it's awfull and I'm not inspired.
Bug fix : adding title insensitive tokenization in french (there was no issue)

_Added 2 xfail tests and reasons, because when a word is tagged as PROPN or AUX it's not lemmatized_

## Types of changes

- [X] **Bug fix** (non-breaking change fixing an issue)
- [X] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:

- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks, this is really nice! This has been outstanding for way too long.

A thought: currently are the lemmatizer files imported by default? I still think it's better to have this data in `.py` files instead of `json`, but I think we should be careful to avoid importing the module until it's used.

**Comment by Gregory-Howard** [comment]
Yeah lemmatizer are already imported for every language. Should I write files with the ```python -m spacy download en``` command ?

**Comment by honnibal** [comment]
It would be nice to find a solution where the languages are lazy-loaded. I'll think about how to do this --- probably a bit of crafty magic in `spacy/__init__.py`.

We wouldn't want to use the `download` command --- that's really just for the large binary data packs.

**Comment by Gregory-Howard** [comment]
Something like this ? : 
``` 
def __init__(self):
    super()
    if not LOOK_UP:
        # wget somerepo/spacy/lang/lemmatize.py
        # or
        # wget http://www.lexiconista.com/Datasets/lemmatization-lang.zip
        # parsing and save in repo
```

**Comment by honnibal** [comment]
Listing out solutions:

1. Lemmatizer data is in repository as .py files
2. Lemmatizer data is in repository as data files
3. Lemmatizer data is packaged in model
4. Lemmatizer data is downloaded in separate mechanism, outside of model

I think 1 is okay --- the only drawback is that we have to make sure that when you do `import spacy`, you don't accidentally load 500,000 lines of lemmatizer data for languages you don't care about. That's why I want some sort of lazy-loading.

Currently the problem is that we import the different languages within the `spacy/__init__.py` file --- and the different languages tend to import the data for the tokenizer etc within their package `__init__.py`.

So currently:

* User does `import spacy`, executing `spacy/__init__.py`
* `spacy/__init__.py` does `import fr, hu, de` etc
* These ultimately execute `import spacy.fr.tokenizer_exceptions, spacy.fr.lemmatizer_data`, etc

Adding up over all the languages, the current tokenizer exceptions are already leading to a lot of data being loaded. I think the lemmatizer data in this PR tips this over into being too much.

What we need is for the data not to be loaded until the user does `nlp = spacy.load('fr')`. At that point, it's fine for the lemmatizer data to be imported and loaded.

**Comment by Gregory-Howard** [comment]
Lemmatization files are already .py not json files.
Created with : https://pastebin.com/Q34YfaWt (need to improve it a bit)

Okay I fully understand the problem. 
http://stackoverflow.com/questions/128478/should-python-import-statements-always-be-at-the-top-of-a-module
>The best reasons I've seen to perform lazy imports are:

> -Optional library support. If your code has multiple paths that use different libraries, don't break if an optional library is not installed.
> -In the __init__.py of a plugin, which might be imported but not actually used. Examples are Bazaar plugins, >which use bzrlib's lazy-loading framework.

**Comment by Gregory-Howard** [comment]
I'm not sure if what I've done works in python 2.7 normally yes but this time it's a **Breaking change**

**Comment by honnibal** [comment]
Really thanks a lot for doing this --- you've really had to wade into lots of not-very-fun details of Python on this. Getting the lemmatization in and getting this all right will be really great.

**Comment by ines** [comment]
Thank you – and I agree, this will definitely make a big difference!

It'll be even better in v2.0 once we've made some more changes to the language data. Now that there are so many languages, things have been getting a little messy again... 

Here are some of the ideas we've had:

* Move all languages to a module `languages` (just need to find a good solution to still allow `from spacy.en import English` etc.)
* Improve the way a `Language` subclass and its `Defaults` are created and make it more obvious which components are needed and where they are coming from (also get rid of random wildcard imports)
* Improve the way tokenizer exceptions are put together – maybe create one, more powerful helper function or class, instead of relying on random helpers like `update_exc()`, `strings_to_exc()`, `expand_exc()` etc.
* Include word lists like `NUM_WORDS` and all the hard-coded stuff that's currently in [`orth.pyx`](https://github.com/explosion/spacy/blob/master/spacy/orth.pyx) with the language data. Each language could define its own functions for things like `like_number`, which are then used to set the respective flags. This would also make it much easier to add more flags in the future.

**Comment by Gregory-Howard** [comment]
>Move all languages to a module languages (just need to find a good solution to still allow from spacy.en import English etc.)
In which file do you want to do `spacy.en import English`?

**Comment by ines** [comment]
@Gregory-Howard Ah, I meant, we shouldn't break backwards compatibility for things like:

```python
from spacy import en
from spacy.en import English
```

At least, I think it'd be a bad idea to just move `spacy.en` to `spacy.languages.en` in v2.0 and break people's code.

**Comment by Gregory-Howard** [comment]
Oh okay, I have no idea how we can allow backwards compatibility for this :/

**Comment by Gregory-Howard** [comment]
Actually we can have into spacy/\_\_init\_\_.py
``` from spacy.languages.en import *
en = spacy.languages.en.English
```
Or 
``` from spacy.languages.en import English as en ```

But with this metho we can't have lazy loading AND backwards compatibility

**Comment by Liebeck** [comment]
@honnibal You opted for "Lemmatizer data is in repository as .py files"

Won't that design be too restrictive for other resources that might clash due to license issues? I'm copying my unaswered comment from #846: 

`Do you want me to include the mapping from IWNLP directly into the code of spaCy? Won't there be a clash between your MIT License and the CC license (which I'm forced to use since the Wiktionary data is CC licensed)? I guess an easy way to circumvent this would be to create a file format/model which can then be downloaded by spaCy?`

**Comment by honnibal** [comment]
@Liebeck I don't think there's a clash. It follows the same logic as porting in code originally released under another license. Two scenarios:

1. The other license is more restrictive, e.g. GPL. In this scenario spaCy can't depend on the data.
2. The other license is less restrictive, e.g. CC-by-SA or Apache. In this situation, I believe we're allowed to distribute the data, including the original license or attribution as necessary.

I don't think exposing the data as text vs as .py files changes anything.

**Comment by ines** [comment]
See #1413 🎉  (closing this PR since it's all covered on `develop` now)

**Pull request closed without merging**
