### PR TITLE
Only generate dev examples once while training

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Instead of regenerating dev examples at each eval step, process the dev corpus more similarly to the train corpus and only generate the dev examples once at the start of training.

### Types of change

Enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
I guess this doesn't cause problems after the change to reset `example.x`?

**Review by honnibal — APPROVED** [review]

**Comment by adrianeboyd** [comment]
Ah, hmm. I think it should be okay. Are there cases where we need to worry about preserving the state of `example.x` at all?

**Comment by adrianeboyd** [comment]
The only concern is speed, and the difference probably isn't major, so we can just close this if you want.

**Comment by honnibal** [comment]
I think I'd rather leave this alone: I don't think it's a major performance improvement, and it makes me nervous that resulting bugs would cause evaluation results to be off. We can revisit the question if we do find the performance gain to be worth it.

**Pull request closed without merging**
