### PR TITLE
[WIP] add basic support for Irish

### PR DESCRIPTION
**Pull request by jimregan**
## Description

This is a work in progress; I'm opening the pull request to make sure it builds with travis

## Types of changes

- [ ] **Bug fix** (non-breaking change fixing an issue)
- [X] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:

- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ines** [comment]
Thanks – this is really cool! 👍

When you have some time, one or two simple tests would be amazing, too. I'd love to port this over onto the [develop branch](https://github.com/explosion/spacy/tree/develop) so we can include it with [spaCy v2.0 alpha](https://alpha.spacy.io/docs/v2), and make use of some of the new features and the simpler language data format.

One new v2 features in particular is the [norm exceptions](https://alpha.spacy.io/docs/usage/adding-languages#norm-exceptions) to ensure that similar words receive the same representation, especially with sparse training data. Considering the Irish tokenizer exceptions contain a lot of `NORM`s, this could be pretty relevant? (I'm no expert on Irish, so I'd be curious to hear your thoughts!)

**Comment by jimregan** [comment]
A lot of them aren't particularly relevant to the modern language, it's just that there's a lot of older text out there and I have to work with it.

I wanted to play with the alpha stuff myself, so I made a stab at porting it myself in #1152

**Comment by ines** [comment]
Thanks a lot for doing the port – looks good and Travis is green!
Just let us know when it's ready and I'll hit merge 😀

**Comment by jimregan** [comment]
Closing, old version

**Pull request closed without merging**
