### PR TITLE
refactoring of pymorphy2 wrapper and handling of repeated normal forms with tests

### PR DESCRIPTION
**Pull request by DSLituiev**
## Description
This addresses #11620 and #11626 by:
- refactoring pymorph2 wrapper out of Russian Lemmatizer into the common `spacy/pipeline/lemmatizer.py`. This ensures that initialization code is not replicated between Russian and Ukrainian (and any other languages pymorphy2 may support, like pre-revolution Russian spelling). 
- in the refactored modified `PyMorhpy2Lemmatizer(Lemmatizer)`, the allowed modes are `in {"pymorphy2", "pymorphy2_lookup"}` to address #11620 
- `pymorphy2_lookup` is modified to better handle unambiguous cases where a text form maps to the same normal form, e.g. `хорошим [(plural, dat), (sing, masc, instr), ...] --> хороший`, see #11626
- `pymorphy2` falls back to `pymorphy2_lookup` if POS of the token is empty, instead of returning the text form

### Types of change
bug fix

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Thanks for looking at this! Let's separate this into two separate PRs:

1. Minimal fix for `pymorphy2_lookup` mode that will go into v3.4.2 (the current `master` branch). I can do this PR.
2. Changes that modify the lemmatizer behavior, which should go into spacy v3.5 (the current `develop` branch) instead of v3.4.2 because it changes the output. I think we have also already switched `develop` to the default as `pymorphy3`, so we should test any changes with the updated version.

Other notes:

* I'd rather keep `spacy.pipeline.lemmatizer` as only the lookups-table-based lemmatizer that uses `spacy-lookups-data`.
* I think it's okay to keep the core implementation in `RussianLemmatizer` and have `UkrainianLemmatizer` extend it, since this is also similar to the defaults in pymorphy2/3.
* You can use `Literal` as `from spacy.compat import Literal`.
* The class variable `RussianLemmatizer._morph` was intended to save memory if you have multiple Russian pipelines loaded in the same script, but memory is not as limited as it was when this was originally implemented, so we could also simplify this by making it an instance variable.

We're planning on releasing v3.4.2 soon so I'll go ahead and do the first PR today.

**Comment by adrianeboyd** [comment]
I wasn't sure whether you were planning to come back to this PR? If you'd prefer, we can put this on our todo list, but it will be relatively low priority.

Given #11631 and the conflicts in this branch, I think it would be easier to start with a new PR (currently against `master` for v3.5), and we'll continue to track the issues under #11625 and #11626.

I'll close this for now, but feel free to reopen or submit a new PR!

**Comment by DSLituiev** [comment]
@adrianeboyd from your comment, I understood that you had plans to modify it. I am open to help, but I am not sure how I can be helpful giving you have multiple versions being baked. Please let me know.

**Comment by DSLituiev** [comment]
Are you suggesting pushing it to `develop` branch? I can do that. I would still prefer to keep inheritance from a common pymorph2 lemmatizer class, rather than Ru>Ukr. If you prefer to keep `spacy.pipeline.lemmatizer` with only one class, I can place it in a separate file within the same folder.

**Pull request closed without merging**
