### PR TITLE
Improved polish tokenizer and stop words.

### PR DESCRIPTION
**Pull request by Gizzio**
## Description

Hi, we (@kowaalczyk @DoomCoder and @MateuszOlko) are working on complementing spaCy with polish language support. This is first PR, which covers tokenizer and stop words improvements and tokenizer tests.

### Types of change
Enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks a lot for this! Looks good.

The LGPL license is a bit of a problem on the exceptions data though :(. We really don't want to complicate the license story on spaCy, which we publish under an MIT license. Having part of the code be LGPL licensed wouldn't work for us.

Is it possible to find an alternative source of the data?

**Comment by tomekkorbak** [comment]
@honnibal  is two-clause BSD license compatible with spaCy's MIT license? We got in touch with the author of tokenizer rules and he's willing to republish under two-clause BSD.

**Comment by honnibal** [comment]
@tomekkorbak Yes, 2-clause BSD would be fine, thanks!

**Comment by Gizzio** [comment]
@honnibal @ines 

It took a while, but finally we have a suitable license. I also added new like-number checking and removed "splitting" exceptions from tokenizer.

As I said, we are working on full support for the polish language. We already have a working rule-based lemmatizer, tag map to UD, the first version of POS tagger (trained on NKJP corpus), and dependency parser (trained on UD). We want to make PR with lemmatization and tag map, but rules in lemmatizer are divided by tags, so our lemmatization and tag map depends on POS tagger. Should we make PR with lemmatizer, or wait for POS tagger to be merged?

**Comment by honnibal** [comment]
Thanks for the changes! Sorry about the delay merging this, I've been traveling.

**Pull request merged**
