### PR TITLE
Allow cupy 12.0 for extras

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Allow cupy 12.0 for extras.

### Types of change

?

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
@explosion-bot please test_gpu

**Comment by adrianeboyd** [comment]
cupy 12.0 is fine, the GPU failures are the ones fixed in #12472.

**Review by svlandeg — APPROVED** [review]
Fine to merge - unless you want to merge in `master` and run the GPU tests again?

**Comment by adrianeboyd** [comment]
No, it seems like a waste to rerun the whole CI.

**Pull request merged**
