### PR TITLE
Improve type annotation for `Language.pipe`

### LINKED ISSUE #8772: Type annotation of `Language.pipe` missing main variant
## How to reproduce the behaviour

Here's an example from the docs of how to use `Language.pipe`:

```python
# Setup code
import spacy

nlp = spacy.load("en_core_web_sm")

# From docs
texts = ["One document.", "...", "Lots of documents"]
for doc in nlp.pipe(texts, batch_size=50):
    assert doc.has_annotation("DEP")
```

Running `mypy` on this file produces the following errors:
```
test.py:7: error: Need type annotation for "doc"
test.py:7: error: Argument 1 to "pipe" of "Language" has incompatible type "List[str]"; expected "Iterable[Tuple[str, <nothing>]]"
test.py:8: error: "Tuple[Any, Any]" has no attribute "has_annotation"
Found 3 errors in 1 file (checked 1 source file)
```

Here's [the type signature of `Language.pipe`](https://github.com/explosion/spaCy/blob/d48c01a6f77a90db06e936ae903d1d0ea151ae31/spacy/language.py#L1437-L1459):

```python
    @overload
    def pipe(
        self,
        texts: Iterable[Tuple[str, _AnyContext]],
        *,
        as_tuples: bool = ...,
        batch_size: Optional[int] = ...,
        disable: Iterable[str] = ...,
        component_cfg: Optional[Dict[str, Dict[str, Any]]] = ...,
        n_process: int = ...,
    ) -> Iterator[Tuple[Doc, _AnyContext]]:
        ...


    def pipe(  # noqa: F811
        self,
        texts: Iterable[str],
        *,
        as_tuples: bool = False,
        batch_size: Optional[int] = None,
        disable: Iterable[str] = SimpleFrozenList(),
        component_cfg: Optional[Dict[str, Dict[str, Any]]] = None,
        n_process: int = 1,
    ) -> Iterator[Doc]:
```

The Python `typing` docs state:

> A series of @overload-decorated definitions must be followed by exactly one non-@overload-decorated definition (for the same function/method). The @overload-decorated definitions are for the benefit of the type checker only, since they will be overwritten by the non-@overload-decorated definition, while the latter is used at runtime but should be ignored by a type checker.

In other words, `mypy` is only looking at the type signature defined with `@overload`, and not the "main" type signature.

To fix this, the main type signature should be copied and added as an `@overload` variant for `Language.pipe`.

Ideally the type signature of the non-`@overload`-decorated definition should also be updated to indicate that it can be called in either form.

Even better, the `as_tuples` `@overload` variant should be modified to use `typing.Literal` (`spacy.compat.Literal`) to help type checkers infer which variant of `pipe` is being called.

## Your Environment

- **spaCy version:** 3.1.1
- **Platform:** macOS-11.4-x86_64-i386-64bit
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_sm (3.1.0)

### PR DESCRIPTION
**Pull request by connorbrinton**
## Description

These changes add a missing overload variant to the type signature of
`Language.pipe`. Additionally, the type signature is enhanced to allow
type checkers to differentiate between the two overload variants based
on the `as_tuple` parameter.

Fixes #8772.

Since `mypy` isn't listed in `requirements.txt`, I wasn't able to come up with a regression test for this issue. I have tested manually and have verified that Mypy now accepts usage of `Language.pipe` with `as_tuples=False` with these changes. If there's interest in including `mypy` as a development dependency and writing a regression test I can add that to this PR 🙂 

### Types of change

Bug fix and minor enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Sure, it would probably make sense to add `mypy` and tests here, too, which looks like it will turn up a few more issues.

As a minimal check, we could add this to the CI, similar to what we do in `thinc`:

```none
  - script: python -m mypy spacy
    displayName: 'Run mypy'
```

I currently get an `INTERNAL ERROR` related to with `tok2vec`, so this may be a minor adventure, but in the end it's probably all something that needs to be addressed in some way.

**Comment by connorbrinton** [comment]
> I currently get an `INTERNAL ERROR` related to `tok2vec`, so this may be a minor adventure, but in the end it's probably all something that needs to be addressed in some way.

I ran into that while manually testing this PR as well. The traceback indicates that the crash originates in `thinc`'s `mypy` plugin. I temporarily disabled that plugin to manually test this PR, but obviously it would be better to get the root issue fixed. I'll file a bug report on the `thinc` repository and see if I can figure out the cause 👍

> Sure, it would probably make sense to add `mypy` and tests here, too, which looks like it will turn up a few more issues.
> 
> As a minimal check, we could add this to the CI, similar to what we do in `thinc`:
> 
> ```
>   - script: python -m mypy spacy
>     displayName: 'Run mypy'
> ```

Agreed, I think that would be a good idea. Since there currently are a number of typing errors, a simple path to getting this check deployed might be:
* Fix the `thinc` `mypy` plugin crash
* Run `mypy` on the codebase
* Add `# type: ignore[<code>]` directives to every problematic line
* Add the `mypy` check to the CI pipeline
* Over time, eliminate the `# type: ignore[<code>]` directives

Adding all of the necessary `# type: ignore[<code>]` directives probably wouldn't be ideal from a `git blame` perspective, but I suppose it will depend on how many lines are affected.

I'll try to figure out the `thinc` `mypy` plugin bug and create a new PR adding a `mypy` check to the codebase within the next week 👍

**Comment by svlandeg** [comment]
Hi @connorbrinton, thanks for looking into this! Let us know how you go. I guess in the meantime I could mark this PR as draft?

Alternatively, we could also merge and add the regression test (hopefully) later. What do you think, @adrianeboyd ?

**Comment by connorbrinton** [comment]
Hi @svlandeg! I went down a bit of a rabbit hole investigating the Thinc Mypy plugin crash (😅), but just finished submitting an issue describing the issue and the cause/potential fix.

I'm happy to wait for a resolution on that issue before merging here with a regression test. Alternatively there are a number of usages of `pipe(Sequence[str])` within the SpaCy codebase (like [this one](https://github.com/explosion/spaCy/blob/175847f92cb89f2515f848c5eda8872af247954f/spacy/cli/evaluate.py#L119)) which I think could serve as effective regression tests once Mypy is enabled across SpaCy's codebase (and `# type: ignore` directives are removed). I'm totally happy with either way 🙂

**Comment by connorbrinton** [comment]
Update here: The fix to the Thinc plugin has been merged so we're just waiting for the next release. In the meantime I've been working on getting Mypy into SpaCy's CI pipeline. The first step is to ignore all current typing failures. Here's a small script to automatically add `# type: ignore[code]` directives to a project:

```python
import re
import subprocess
from pathlib import Path
from typing import List

import typer


ERROR_RE = re.compile(r"(?P<filepath>.*?):(?P<line_number>\d+): error: .* \[(?P<error_code>[\w\-]+)\]")


@typer.run
def main(
    files: List[Path] = typer.Argument(
        ...,
        exists=True,
        file_okay=True,
        dir_okay=True,
        readable=True,
    )
) -> None:
    """Execute Mypy on the given files and add `# type: ignore[error-code]` directives"""
    # Execute Mypy on the given files
    completed_process = subprocess.run(
        (
            "python",
            "-m",
            "mypy",
            "--show-error-codes",
            *[str(file) for file in files],
        ),
        capture_output=True,
    )

    # Extract structured representation of each error
    for match_groups in ERROR_RE.findall(completed_process.stdout.decode()):
        filepath, line_number, error_code = match_groups

        # Apply # type: ignore[code] directive to the file
        with open(filepath, "r") as source:
            # Read all lines
            lines = source.readlines()

        # Look up the line to modify
        line = lines[int(line_number) - 1]

        # Add directive, working around newline at end of line
        line = f"{line[:-1]}  # type: ignore[{error_code}]{line[-1]}"

        # Store updated line
        lines[int(line_number) - 1] = line

        # Rewrite file
        with open(filepath, "w") as sink:
            sink.writelines(lines)
```

It's still pretty hacky (for example, doesn't handle lines that already have a `# type: ignore` directive) and needs to be run multiple times (since Mypy output changes once initial errors have been ignored), but hopefully is a step in the right direction 🙂

I'll keep working on it until it can automatically get hide all Mypy-discovered errors. That way the "regression test" for this PR can be removal of specific `# type: ignore` directives, rather than an additional (potentially slow) Mypy invocation

**Comment by svlandeg** [comment]
@connorbrinton : Thinc 8.0.9 with your bugfix for the `mypy` plugin is now released and Thinc's version bumped on `master`, so hopefully you can continue with this PR? Feel free to leave it in draft while you're working on it though!

**Comment by connorbrinton** [comment]
> Thinc 8.0.9 with your bugfix for the `mypy` plugin is now released and Thinc's version bumped on `master`, so hopefully you can continue with this PR?

@svlandeg Awesome! I went ahead and created a new PR since ignoring existing Mypy errors affects a large number of lines:
https://github.com/explosion/spaCy/pull/9167

Once that PR is merged I'll rebase this one and remove the `# type: ignore` directives hiding the errors this PR will fix :+1:

**Comment by svlandeg** [comment]
Closing in favour of PR https://github.com/explosion/spaCy/pull/9167 where these edits have been added to 🎉

**Pull request closed without merging**
