### PR TITLE
Add forte to universe.json

### PR DESCRIPTION
**Pull request by mylibrar**
Add forte to the spaCy universe.

## Description
Add a new entry forte(https://github.com/asyml/forte) to universe.json.
Forte is a toolkit for building Natural Language Processing pipelines, featuring cross-task interaction, adaptable data-model interfaces and composable pipelines. Forte is integrated with SpaCy API, making it easy to use as part of a heterogeneous pipeline.

### Types of change
document change

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the PR! forte looks like a cool project.

However, I was unable to install it in a clean virtualenv with Python 3.9 on Linux - I had a build failure with typed-ast. I need to spend more time with this but are there any install related issues you're aware of ?

**Comment by mylibrar** [comment]
Thank you for the notice! Forte supports python 3.6 and 3.7, and currently it cannot be installed with python3.9 because some of dependencies would be outdated. We are trying to make some updates and tests to make it compatible with python3.9.

**Comment by polm** [comment]
Thanks for the info! With Python 3.7 I was able to install Forte and run your demo code. 

I'm going to go ahead and accept the PR, but note that the [homepage link on PyPI](https://pypi.org/project/forte.spacy/) gives a 404, would be great if you could fix that.

**Comment by mylibrar** [comment]
Thank you for the feedback! https://pypi.org/project/forte.spacy/ is up now. You can try and see if it works:
image

**Comment by polm** [comment]
No, that page was already up. On that page there is a "Homepage" link, which has this url:

https://github.com/asyml/forte_wrappers/spacy

That gives a 404.

**Comment by mylibrar** [comment]
The homepage link on https://pypi.org/project/forte.spacy/ is updated. Now it should lead to a [github repo](https://github.com/asyml/forte-wrappers/tree/main/src/spacy).

**Comment by polm** [comment]
Great, it works - thanks!

**Pull request merged**
