### PR TITLE
Return doc offsets in Matcher on spans

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

The returned match offsets were only adjusted for `as_spans`, not generally. Because the `on_match` callbacks are always applied to the doc, the `Matcher` matches on spans should consistently use the doc offsets.

### Types of change

Bug fix.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
This is mildly breaking, but it corresponds to the API docs and I think running the matcher on spans is not particular common. (I'm actually surprised no one has complained about `on_match` for spans yet.)

**Comment by adrianeboyd** [comment]
Yeah, it may well be too breaking, but it's dissatisfying that there's no way for callbacks to work on spans at this point. I suppose if no one is doing this, then it doesn't really matter. I suppose we could consider it for v4.

**Comment by svlandeg** [comment]
Yea, fixing this in v4 feels safer to me!

**Comment by adrianeboyd** [comment]
(This will fail due to typer until `v4` is also updated.)

**Review by svlandeg — APPROVED** [review]
Looks like this is fine to merge into v4, right Adriane?

**Comment by adrianeboyd** [comment]
If we're sure we want to make this change: sure.

**Comment by svlandeg** [comment]
I do feel like this is a bug fix, and no one else seems to object, so let's get this in for `v4` yea :-)

**Pull request merged**
