### PR TITLE
Solving #1494

### PR DESCRIPTION
**Pull request by fsonntag**
## Description
See #1494.

### Types of change
Changed behaviour of tokenizer infix search. When infix_start equals the current offset, previously the whole infix tokenization was skipped. Now we add the infix itself, but still ignore the previous tokens (which are basically not there.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Looks good! I'll hold off on merging this until I've played with it more thoroughly, but it certainly seems elegant. Test looks good too.

**Comment by honnibal** [comment]
What happens if we have your pattern and just `hello 3test`? This will segment into `hello, 3, test` -- so the infix pattern will match at the start of the token, like a prefix. This will be against the intentions of the pattern, since if you want to split that, you should put the logic in the prefix pattern.

It seems like we can cover this case by setting a variable `start_before_infixes = start` before looping over the infix matches. We can then check `infix_start == start_before_infixes` to `continue` the loop as before. This should split `hello...test` into `hello, ., ., ., test` if you have `.` as an infix, without splitting `hello .test`.

**Comment by honnibal** [comment]
Awesome, thanks!

**Comment by fsonntag** [comment]
I have to say thank you for this great tool :)

**Pull request merged**
