### PR TITLE
[WIP] attempt a port from #1147

### PR DESCRIPTION
**Pull request by jimregan**
## Types of changes

- [ ] **Bug fix** (non-breaking change fixing an issue)
- [X] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:

- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ines** [comment]
Hi, just checking in – is this ready to merge? 😀

**Comment by jimregan** [comment]
I meant to add a test, I think. I'm in the middle of writing my dissertation so I haven't got a lot of free time right now, but I'll see about adding a test tomorrow.

**Comment by ines** [comment]
No worries – we're totally happy to leave the PR open! I just wanted to make sure you're not sitting around waiting for us to merge your PR or think we're ignoring it. I'll add the `wip` label to it so you can come back and updated it any time.

Thanks again for the great work!

**Comment by ines** [comment]
Sorry, I hope you don't mind me messing with your PR – just fixed the syntax error and was trying to figure out what went wrong in the last build, because it's an interesting error (potentially a bug? not sure, will investigate!)

**Comment by jimregan** [comment]
I'm absolutely fine with it, it was making me go cross-eyed :)

**Comment by ines** [comment]
@jimregan Cool! Let me know when we can merge 👍 

About the punctuation rules: If I read this correctly, `B'fhearr` has to be `B'` + `fhearr` and can't be `B` + `'` + `fhearr`, right? This is a bit tricky for a simple infix rule, but you could try adding suffix rule like `['][A-Za-z]+` to basically define a suffix as `'` plus alpha characters? And then just import the base rules and add it. Untested, but might work.

```python
suffixes = TOKENIZER_SUFFIXES + [r"['][A-Za-z]+"]
```

**Comment by jimregan** [comment]
@ines looks good to go now (finally!). Thanks for your help!

**Pull request merged**
