### PR TITLE
Tiny correction in french lookup dictionary

### PR DESCRIPTION
**Pull request by mhham**
## Description
Correct the lemmatization of "nombres",  which changed from "nombre" to "nombrer" from spacy 2.0 to spacy 2.1

## Checklist
- [ ] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
cc: @amperinet @mauryaland – could you help review this? 🙂

**Comment by amperinet** [comment]
Yes, sure! 
It looks fine to me. Thank you @mhham for spotting this error ; the lemma for "nombres" is "nombre".

**Comment by mauryaland** [comment]
Looks legit to me! It is one of numerous examples in the lookup table where the lemma form for a plural noun is an infinitive verb. This is due to the fact that the plural/singular form of a noun is the same as one form of the conjugated verb. However, we often want the singular noun as a lemma because the verb is underused. Another example was 'mondes' -> 'monder'.

If I remember well, @amperinet  already did a great work about cleaning a lot of them.

**Comment by ines** [comment]
Perfect, thank you so much! 👍

**Pull request merged**
