### PR TITLE
Support single value for attribute list in doc.to_array

### PR DESCRIPTION
**Pull request by ramananbalakrishnan**
## Description
- Updates `Doc.to_array(attr_ids)` to accept a single value in `attr_ids`
- Partial fix for discussion in issue https://github.com/explosion/spaCy/issues/1410.

## Types of changes

- [x] **New feature** (non-breaking change adding functionality to spaCy)

## Checklist:

- [x] My change requires a change to spaCy's documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ramananbalakrishnan** [comment]
I am not a Cython expert, so could not get the `reshape` command working as-is. If there is a better to way to achieve the same result, do let me know.

Also, can I use directly use [`intify`](https://github.com/explosion/spaCy/blob/cd9378c8/spacy/attrs.pyx#L98) to map a string name ("LEMMA") in the input list to the attribute id (`spacy.attrs.lemma`) ?

**Comment by ramananbalakrishnan** [comment]
I have ported the changes over to the `develop` branch as well, for merging into v2.  ( PR https://github.com/explosion/spaCy/pull/1440 )
I should be able to keep track of suggestions from either PR and fix across both branches.

**Comment by honnibal** [comment]
Thanks for this! It will be merged in time for the new v2 release.

**Comment by honnibal** [comment]
> Also, can I directly use intify_attrs to map a string name ("LEMMA") in the input list to the attribute id (spacy.attrs.lemma) ?

I *think* so. It's possible there's some quirks, but yes that's what we would want to be using.

**Comment by ramananbalakrishnan** [comment]
Done. `to_array` now supports string names in `attr_ids`.
Updated tests and the v2 PR as well.

**Comment by honnibal** [comment]
:tada:

Thanks for this! Made some small changes, especially changing use of `type` in the conditionals. This is a little bit like the weird equality checking stuff in Javascript --- it's best to avoid type-based checks in Python if possible, because the language makes it hard to make the logic fully correct. `hasattr` checks are ugly, but it's a bit easier to cover all the cases this way.

**Comment by ramananbalakrishnan** [comment]
got it! looks much cleaner now.

Also, since you are directly returning `output.reshape()`, looks like the `output_1D` variable is redundant now.

**Pull request merged**
