### PR TITLE
Adding MindMeld to Universe JSON

### PR DESCRIPTION
**Pull request by KKsharma99**
Mindmeld is a conversational AI platform for deep-domain voice interfaces and chatbots. https://www.mindmeld.com/

Adding MindMeld to Spacy Universe. MindMeld is a conversional AI platform. (MindMeld includes an inbuilt automatic query annotator that levarages Spacy's NER https://www.mindmeld.com/docs/userguide/auto_annotator.html.)

## Description

Added an entry for MindMeld in universe.json.

### Types of change

An enhancement.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Wow, super cool! Happy to feature this. Sorry about the CLA thing, it wouldn't be necessary just for changes to the website, but thanks for filling out the bureaucracy anyway.

**Comment by KKsharma99** [comment]
No worries, thank you for merging this update!

**Comment by minhtuev** [comment]
@honnibal : just checking, not sure why MindMeld is not featured on this page yet:
https://spacy.io/universe

**Comment by adrianeboyd** [comment]
Ah, thanks for the reminder. The updates should be reflected on the website in a few minutes.

**Pull request merged**
