### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Remove duplicate section about compiling from source
* Recommend `pip install --no-build-isolation --editable`

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
I'll leave this open for further changes related to #6887.

**Comment by adrianeboyd** [comment]
(The `*.md` exclusion isn't working here, either. I'm not sure what's going on.)

**Comment by ines** [comment]
> (The *.md exclusion isn't working here, either. I'm not sure what's going on.)

I feel like this never worked properly, even though (I think?) we configured it exactly as documented in the Azure Pipelines docs. Or maybe I misunderstood what it's supposed to do? 🤷‍♀️

**Comment by adrianeboyd** [comment]
I don't have anything more to add right now. We might have to add more instructions related to the isolated builds and numpy soon.

**Pull request merged**
