### PR TITLE
Serialize _context separately in multiprocessing pipe

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Serialize _context separately for multiprocessing pipe

### Types of change

Bug fix.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
But `_multiprocessing_pipe` uses `Doc.to_bytes()`.

**Comment by honnibal** [comment]
Oh Crap. Right, okay.

**Comment by adrianeboyd** [comment]
That might work, yeah.

**Comment by honnibal** [comment]
Nice, LGTM

**Comment by adrianeboyd** [comment]
Well, it would work if `_context` got pickled with the `Doc`, argh...

**Comment by svonava** [comment]
Hey everybody - first of all, spacy is awesome!

I'm seing some weird interplay between as_tuples and multiprocessing.

What I did:
1. Use en_core_web_lg, run nlp.pipe() over 1k docs with batch_size 100, n_process 10.
2. I assume that A & B can have different order here: "for A in nlp.pipe(B)" and I turned on as_tuples to align A & B after the pipe is done.
3. as_tuples=True made my code take an order of magnitude more ram, as if only once I set this true it actually creates 10 different representations of en_core_web_lg in memory.

Is this expected? Does this mean that when as_tuples=False, the multiprocessing doesn't separate the processes properly?

Thank you for any elaboration on this!

**Comment by adrianeboyd** [comment]
Please open a new discussion thread rather than commenting on a older PR.

**Pull request merged**
