### PR TITLE
Remove deprecated methods: Doc.print_tree, Doc.merge, Span.merge

### PR DESCRIPTION
**Pull request by ines**
## Description

These have been deprecated for a while and shouldn't be used anymore, so we might as well remove them for v3.

### Types of change

enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
It looks like the `collu.py` script still uses `doc.merge` ... 
and `custom_component_entities.py` and `custom_component_countries_api.py` still use `span.merge` :|

**Comment by adrianeboyd** [comment]
I think the `conllu.py` script can probably go. I don't think it works 100% with `master` and it would definitely need a ton of updates for v3. Using `spacy convert` is probably better in general. We can add an example project for this kind of thing?

**Comment by svlandeg** [comment]
It would definitely be good to clean out the examples dir. I don't always know the history of those and whether or not they are still useful.

**Comment by ines** [comment]
I've added a task for cleaning out the examples directory to the v3 board  👍 And yes, I think for v3, we should want fewer of these arbitrary scripts and move the more complex stuff out to projects.

**Pull request merged**
