### PR TITLE
Adding PhruzzMatcher to spaCy universe

### PR DESCRIPTION
**Pull request by mjvallone**
Adding PhruzzMatcher to spaCy universe

## Description

PhruzzMatcher is a combination of the RapidFuzz library with Spacy PhraseMatcher The goal of this component is to find matches when there were NO "perfect matches" due to typos or abbreviations between a Spacy doc and a list of phrases. To see more about Spacy Phrase Matcher go to https://spacy.io/usage/rule-based-matching#phrasematcher

### Types of change

New component to add in the spaCy universe.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the submission, looks like a cool project! 

About the sample code - it doesn't really do anything, could you make an example that actually has output and shows what data your code sets? It would also be better to use `spacy.blank("es")` so the user doesn't have to download a model if the code doesn't depend on it.

Another thing is your Python package doesn't specify rapidfuzz as a dependency, so if you just `pip install phruzz_matcher` it doesn't work.

**Comment by mjvallone** [comment]
@polm I fixed it, thanks for your suggestions! :)
Please feel free to test it again

**Comment by polm** [comment]
Excellent, thanks for the changes!

**Comment by lingvisa** [comment]
Is this a mature project?

**Comment by polm** [comment]
Hey @lingvisa, Universe is intended as source of information, not as a list of verified components, and while we run a few basic checks before adding things we don't thoroughly vet projects. Making judgments about project maturity is ultimately up to you.

**Pull request merged**
