### PR TITLE
Use max(uint64) for OOV lexeme rank

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Use max(uint64) for OOV lexeme rank

### Types of change

Bug fix.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
The tests will fail because the version of thinc isn't available.

Is there a better way to define OOV_RANK in a way that's fast in Lexeme and elsewhere?

**Comment by honnibal** [comment]
I think we can do:

```
from cython.stdint cimport UINT64_MAX as `OOV_RANK`
```

We can do that in `spacy.lexeme`. We'd probably need a Python function or Python variable with the value as well to make it accessible to modules like `spacy.util`

**Comment by adrianeboyd** [comment]
`util` isn't a great place to put it but nothing else seemed better and I was trying not to call a function if possible. If you want to call a function in the python parts, I think you may as well use `numpy.iinfo(numpy.uint64).max`. How about this version with no local math?

**Comment by honnibal** [comment]
Okay, looks good!

**Pull request merged**
