### PR TITLE
Removed a manual file handler pitfall (Pylint R1732 consider-using-with code)

### PR DESCRIPTION
**Pull request by NaelsonDouglas**
## Description
There was a part in the code where a file stream was being open manually.  I just changed the code in order to open the file into a with block.

### Types of change
Refactoring

### CODE REVIEW

**Comment by polm** [comment]
Thanks for catching that! Looks good to me.

**Comment by adrianeboyd** [comment]
For background: this code was adapted from `numpy`, but it looks like they're using a totally different approach as of the end of 2020. Maybe we should rework all of this...

**Comment by NaelsonDouglas** [comment]
> Not quite, we want this to continue, probably silently, if it can't write to this file.

@adrianeboyd  I silenced it on [here](https://github.com/explosion/spaCy/pull/9471/commits/7754f11f7607272b1c16f941e6541fc9c018968a) :)

**Comment by svlandeg** [comment]
Hi @NaelsonDouglas , the proposed changes actually change the semantics of the code, as the current version doesn't catch any exception but instead would reraise it. We'll go ahead and close this, as this part of the code base is too risky to make minor style fixes too, risking bugs or changed behaviour. I hope you understand!

**Pull request closed without merging**
