### PR TITLE
util.filter_spans possibility to remove longest spans

### PR DESCRIPTION
**Pull request by JAugusto97**
## Description
The util.filter_spans function only provides the option of removing the smallest spans. This modification makes it possible for the user to select if he wants to remove the smallest or the longest spans. 

### Types of change

Enchancement
## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Hi, this is a nice idea, but I'm hesitant to support too many options in the core library because I'm worried it will become difficult to maintain and document, see a related discussion here:

https://github.com/explosion/spaCy/discussions/7355#discussioncomment-487435

In this case, you would also probably want to change the sort key, since for overlapping spans, this will return the last span rather than the first span.

**Comment by JAugusto97** [comment]
> Hi, this is a nice idea, but I'm hesitant to support too many options in the core library because I'm worried it will become difficult to maintain and document, see a related discussion here:
> 
> [#7355 (reply in thread)](https://github.com/explosion/spaCy/discussions/7355#discussioncomment-487435)

Thanks for your answer!

I would suggest adding this enhancement to filter_spans despite the given counterpoint because I believe this function follows a similar concept of a sorting function in python. I think no method is "more important" than the other. Only being capable of removing the smallest overlapping spans would be similar to not having the "reverse" option in the sorted function. The option depends on the application, as mine would require this modification.

> In this case, you would also probably want to change the sort key, since, for overlapping spans, this will return the last span rather than the first span.

Sorry, I'm not sure I understood what you meant. The last span is the smallest overlapping span after sorting, which we want if longest=True. I've tested this function, made some test cases and It seems like it is behaving as it should. A simple example with 3 overlapping spans and one non-overlapping span like:
spans = [(5, 9), (14, 29), (20, 29), (25, 29)]

returns [(5, 9), (25, 19)], as it should.

Sorry if I'm missing something and thanks again for the answer!

**Comment by adrianeboyd** [comment]
Sorry, I didn't explain that well. If you have overlapping spans of the same length, this prefers the later span rather than the earlier span. The second sort key `-span.start` + `reverse=True` works to prefer the earliest span for the longest spans of the same length, but if you want the shortest spans, then it's `start` + `reverse=False`.

**Comment by adrianeboyd** [comment]
Hi, thanks again for the PR, but we discussed this internally and decided that we want to keep this function as it is without any additional options. It should hopefully not be too difficult for users to implement custom filtering methods as needed for their tasks.

**Pull request closed without merging**
