### PR TITLE
[v1.x] Backport 2.x's avoidance of 'import pip'

### PR DESCRIPTION
**Pull request by mdcclv**
## Description
pip v9.0.2 has mercilessly broken anything that runs `import pip`: see https://github.com/pypa/pip/issues/5079 (and, for lolz, https://github.com/pypa/pip/issues/5081)

You can reproduce for spaCy 1.x by doing (in a virtual environment):
```
pip install --upgrade pip
pip install spacy==1.10
python -m spacy
```
and observe this error:
```
Traceback (most recent call last):
  File "/Users/orionmontoya/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/orionmontoya/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/orionmontoya/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/spacy/cli/download.py", line 9, in <module>
    from .link import link_package
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/spacy/cli/link.py", line 4, in <module>
    import pip
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/orionmontoya/spacy-demo-venv/lib/python3.5/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```

Pip is imported only to check `is_package` when downloading models, and spaCy 2.x has a better implementation, using setuptools' `pkg_resources`. Since I have several projects still dependent on Spacy 1.x, I would rather not do pip's workaround on pinning to `pip==9.0.1`. So I backported what was in 2.x.

It seems to me that is a showstopper that merits a patch release.

### Types of change
Bugfix backport of 2.x code (and test).

When I tried to run the tests locally in my venv I got `ImportError: No module named 'spacy.gold'` and I'm not 100% sure why (didn't have this issue on prior PRs). But it runs fine in Travis.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by StephenTurley** [comment]
Is there a workaround for this?

**Comment by StephenTurley** [comment]
I was able to get it working by explicitly pinning the pip version for anyone else needing a workaround until this gets merged. 
`pip3 install pip==9.0.1 spacy==1.8.2`

**Comment by mdcclv** [comment]
You can of course also install the _current_ version with pinned pip:
```pip install pip==9.0.1 spacy==1.10```
or if anyone wants to install this branch and confirm it works for them with 9.0.2:
```pip install pip==9.0.2 git+https://github.com/mdcclv/spaCy.git@backport_pip_independence```
(you'll also need the build dependencies for spaCy AFAIK)

In particular, I notice that this PR assumes that `pkg_resources` is available, which is true only if `setuptools` is present. That will be true for anyone who uses pip, but it might not be true for 100% of users. Especially us cranks who are still on the 1.x versions.

**Comment by bm371613** [comment]
@mdcclv To satisfy support both `pip==9.0.1` without `pkg_resources` and the latest pip with `setuptools` present, would you accept a try-except around `import pkg_resources` that would fall back to pip-based method if necessary?

**Comment by mdcclv** [comment]
If `pip` is present, then `setuptools` is present, and if `setuptools` is present, then `pkg_resources` is necessarily present. So in both cases `pkg_resources` will be present anyway. To my mind the potential absence of `pkg_resources` is pretty theoretical, and it can't be categorically ruled out.

An easy guarantee would be to replace the pip dependency in `requirements.txt` with a `setuptools` dependency, but even that seems unnecessary: is there anybody who fetches the deps from `requirements.txt` without using something that uses `pkg_resources`?

**Comment by bm371613** [comment]
If `import pip` can succeed only if `import pkg_resources` is also possible, this PR is not introducing the problem you mention - it was already there. I don't mean to hurry too much, but this is a fix for a problem conerning all 1.x users, who now have to come up with hacky fixes or push `pip==9.0.1` to users of their libraries. Whether this "no `pkg_resources` available" user group actually exists and what to do about it can be dicussed later.

**Comment by mdcclv** [comment]
@bm371613 I agree: I'd love to see this merged — @ines is there anything more I can do to help support a patch release?

**Comment by ines** [comment]
Yes, we can definitely release a patch for `v1.x`, that's no problem! We'll just do this alongside `v2.0.10`.

**Comment by mdcclv** [comment]
Pip 9.0.3 https://github.com/pypa/pip/releases/tag/9.0.3 fixes the situation that causes this, so this is less urgent now, but presumably still worth doing!

**Pull request merged**
