### PR TITLE
Allow binarized vectors to save memory

### PR DESCRIPTION
**Pull request by forgetso**
## Description
It is possible to binarize existing word embeddings so that they use 37.5 times less memory and perform a top-k query 30 times faster (See [Near-lossless Binarization of Word Embeddings](https://arxiv.org/pdf/1803.09065.pdf)). spaCy should be able to init models and perform most_similar calculations using binary vectors. This pull request enables spaCy to do this by checking the data type of vectors during init-model and by using an appropriate similarity function in most_similar.

### Types of change
Enhancement

## Checklist

- [X] I have submitted the spaCy Contributor Agreement.
- [X] I ran the tests, and all new and existing tests passed.
- [X] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
This is a neat idea but unfortunately I don't think I want to accept this change. I'm worried about the implementation complexity that will result from this, as there are lots of other places in the code that will try to use the vectors and be surprised to get back non-float results. 

There's already many places where I think this implementation will fail, for instance in the the `doc.vector`, `token.vector` and `lexeme.vector` methods, and also in the `StaticVectors` layer which uses the vectors in the models.

**Comment by forgetso** [comment]
This is a good point. The Sokal Michener similarity function (or similar) and dtypes would need to exist in:

- spacy/lexeme.pyx
- spacy/tests/util.py
- spacy/tests/vocab_vectors/test_similarity.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/tokens/token.pyx
- spacy/vectors.pyx
- spacy/vocab.pyx

I have modified the above to include a dynamic similarity function and also allowed `dtype` to be specified when `reset_vectors` is called in `vocab`. `dtype` is then passed through to `Vectors` and is set to `"f"` if it is `None`. `vectors_dtype` is set as a property in `vocab` also. The tests are passing and I added new tests into `test_similarity.py` for binarized vectors.

I'm not entirely comfortable with the implementation however as it involves repeating the same similarity functions in each of `doc`, `span`, `token`, and `vocab`. Is there a common place where these should be stored?

The only other mentions of `"f"` or `"float32"` seem to be in pipes.pyx which I _think_ is training. I don't think there is any need to change dtypes here as binarization should only be applied to pre-trained vectors.

`StaticVectors` seems to just load the vectors as is from spacy.

`VECTORS[key] = nlp.vocab.vectors.data`

It might work if you loaded binarized vectors into spacy and then passed them to thinc for ML purposes. However, it's probably not expected behaviour to be working with these kind of vectors for ML in the first place.

**Comment by honnibal** [comment]
It's just that it's really the sort of change that I've found comes back to haunt us :(. Suddenly this data type can be two different things, and there's no way to abstract it without ruining the efficiency that motivates it. And then developers will easily forget that it can be two data types, because they're only using one. 

I think the problem is pretty fundamental so I don't think you should spend more time on the patch. It's a shame because I do really appreciate the effort to open the PR, and I can see how the paper is appealing. It's just that there are some techniques that would be worth it for a specific code-base and model, but can't really work in a more general framework like spaCy that is designed to accommodate many use-cases.

**Comment by forgetso** [comment]
That's ok. I needed it for my own stuff anyway. I'm only using pre-trained models - not doing any training myself - to tag millions of records using my PC. As I have limited RAM and GPU RAM, it makes sense for me to work with binarized vectors as my GPU was not able to handle the Common Crawl model whilst also running n most_similar on thousands of vectors.

I also patched this into my fork of spaCy that stores the vectors data in shared memory. It turns out that this requires two separate classes of vectors (int and float) because of how Cython works. There are more details [here](https://github.com/explosion/spaCy/issues/5051) should you ever decide to go down this route.

**Pull request closed without merging**
