### PR TITLE
Add Amharic language stop words.

### PR DESCRIPTION
**Pull request by tewodrosm**
## Checklist

- [ ] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by yosiasz — COMMENTED** [review]
@tewodrosm these were good stop words. why did you close the PR?

**Comment by tewodrosm** [comment]
sorry [yosiasz ](https://github.com/yosiasz) i am new to Github

**Comment by tewodrosm** [comment]
sorry [yosiasz](https://github.com/yosiasz) that was a mistake. I am new to Github, this is my first pull request.

**Comment by svlandeg** [comment]
Because we merged the previous PR by @yosiasz into spaCy's `master` branch, this PR now has some "conflicts" that need to be resolved. You can do this locally by merging the current spaCy `master` branch in your local branch, resolving the conflicts, and then pushing.

If that feels to complicated - you could also start from scratch, create a new branch from spaCy's current `master`, and make the changes again (it looks like there's just some new exceptions and stop words, so that should be doable)

**Comment by svlandeg** [comment]
Closing this one - salvaged the improved stop list in the PR here: https://github.com/explosion/spaCy/pull/6864

**Pull request closed without merging**
