### PR TITLE
Adding LingFeat Software to spaCy Universe.

### PR DESCRIPTION
**Pull request by brucewlee**
## Checklist

- [ X] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ X] I ran the tests, and all new and existing tests passed.
- [ X] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the submission! There was an issue with your JSON formatting, which is why the tests failed, but I fixed it.

Not a major issue, so I'll go ahead and merge this, but your thumbnail image is huge at over 1000px on a side - the recommended size is more like 100px square.

**Comment by adrianeboyd** [comment]
And a side note: I didn't work on readability assessment myself, but Detmar Meurers was my PhD advisor, and it's really nice to see new work in this area, especially with the attention paid to linguistic features!

**Comment by brucewlee** [comment]
Thanks for all the recommendations!

@adrianeboyd Wow. Dr. Meurers is legendary here. What great news buddy!

**Comment by brucewlee** [comment]
@polm Yup I'll take care of that soon.

**Pull request merged**
