### PR TITLE
Adding አማርኛ (am-et) language support

### PR DESCRIPTION
**Pull request by yosiasz**
## Description
Adding Amharic to spaCy. This PR is still work in progress. I have also created and ran some unit tests

### Types of change
Adding a brand new language: Amharic

## Checklist
- [ X] I have submitted the spaCy Contributor Agreement.
- [ X] I ran the tests, and all new and existing tests passed.
- [ X] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
This is very cool! As you mentioned the PR is still WIP, I converted it to a draft for now.

Feel free to push "ready for review" button whenever you think the PR is ready!

**Comment by yosiasz** [comment]
@svlandeg thanks for your guidance. tests are failing. Should I still submit for review?

**Comment by svlandeg** [comment]
No - you'd want to make sure the tests all go green first ;-)

**Comment by svlandeg** [comment]
Oh wait, I only just saw that you're merging the branch into `develop`. That is the branch where we're currently developing spaCy v3. Is this what you meant to do? Are you testing locally with v2 or v3?

**Comment by yosiasz** [comment]
> Oh wait, I only just saw that you're merging the branch into `develop`. That is the branch where we're currently developing spaCy v3. Is this what you meant to do? Are you testing locally with v2 or v3?

oops. Maybe you can create me an amharic branch or do you want me to pull request straight into master/,aster? I forked from master.

All tests pass on my computer :)

image

**Comment by svlandeg** [comment]
Ah, that would explain the failures. You can make the PR directly to `master`. I'm afraid that may mean you'll need to close this one and open a new one ;-)

**Comment by yosiasz** [comment]
hello @svlandeg I am ready to move forward with Amharic, wow it has been 4 years!?!? Life happened :( I will restart this whole effort from scratch

**Pull request closed without merging**
