### PR TITLE
Add mlflow to spaCy universe

### PR DESCRIPTION
**Pull request by louisguitton**
## Description

In its recent 1.8.0 release, `mlflow` introduced the `mlflow.spacy` module with support for logging and loading spaCy models https://github.com/mlflow/mlflow/pull/2242 .

In this PR, I add MLflow to the spaCy universe, as it now has official support.

### Types of change

Change to the website only

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

Currently building the site locally, once it's done and I've tested my change, I'll mark the PR as ready

### CODE REVIEW

**Comment by louisguitton** [comment]
I'm following https://github.com/explosion/spaCy/blob/master/website/README.md#setup-and-installation-setup to get a local build of the website.
`npm install` fails due to `gatsby-transformer-sharp`.

I'm unable to debug what's happening because the stacktraces are huge and JS dependencies are quite beyond me 😂 . Am I missing a step in the setup? I'd like to check how my JSON renders before submitting this PR.

```sh 
# this fails
npm install gatsby-transformer-sharp gatsby-plugin-sharp
```

**Comment by louisguitton** [comment]
Turns out it seems fixed now with 
```sh
npm install gatsby-plugin-sharp gatsby-plugin-manifest gatsby-remark-images-contentful gatsby-source-contentful gatsby-transformer-sharp gatsby-transformer-sqip
npm audit fix
```
(not sure which one of the 2 fixed it)

But it now fails with 
```
  WorkerError: Processing /Users/louis.guitton/workspace/spaCy/website/docs/images/course.jpg failed
  Original error:
  spawn /Users/louis.guitton/workspace/spaCy/website/node_modules/cwebp-bin/vendor/cwebp ENOENT
```

**Comment by adrianeboyd** [comment]
Getting the website working locally can be a bit of a pain. Here's what the preview looks like on my end:

Screenshot_2020-04-27_13-48-23

In you really want to run it locally, I can add that I got things working locally last year with node v10.16.3 (linux) and Sofie just recently with v11.15.0 (windows). We are never ever updating. :grin:

**Comment by louisguitton** [comment]
Thanks a lot @adrianeboyd , made me realise that I was missing a line in the code sample (now added in L2148) and that the logo needed to be with black letters (L2128).
The PR should now be ready. I will not try to get the website setup :P

**Pull request merged**
