### PR TITLE
Sync develop and master

### PR DESCRIPTION
**Pull request by ines**
## Checklist

- [ ] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
I think the sync should have been up-to-date as of #6227. I intentionally skipped the tag map and morph rules PRs and handled a bunch of python2/v3 updates / merging for the other PRs up to this point.

**Comment by adrianeboyd** [comment]
(I think I rebased too much to make it look cleaner and that was a mistake for this workflow?)

**Comment by ines** [comment]
Yeah, I noticed there wasn't really anything to update or any real conflicts... but for some reason, Git(Hub) still thought a clean merge wasn't possible? 🤷‍♀️ So I guess we just have to keep doing this dance and merge one into the other to make it happy.

**Comment by adrianeboyd** [comment]
But there are a bunch of commits listed that we don't want? I am confused...

**Comment by ines** [comment]
Yeah but otherwise, that history would be gone... so I think the idea is: we update the branch with all commits, resolve the conflicts they create, remove what we don't want and then we have a clean merge. And then as far as Git(Hub) is concerned, it's as if we had updated `master` and then made changes to it on `develop` to end up with the latest state.

**Pull request merged**
