### PR TITLE
Capture more noun chunks

### LINKED ISSUE #1226: Include appositional modifiers in english_noun_chunks
I noticed in some parses that appositional modifiers (`tok.dep_ == 'appos'`) are excluded from `spacy.syntax.iterators.english_noun_chunks` (and therefore `Span.noun_chunks`, `Doc.noun_chunks`).  The description of these terms in https://nlp.stanford.edu/software/dependencies_manual.pdf says they are NPs, and so I think should therefore be included as noun_chunks.

This could be accomplished easily by adding `'appos'` to the `labels` list at https://github.com/explosion/spaCy/blob/master/spacy/syntax/iterators.pyx#L13  (I'd offer a P.R. but haven't yet set up a spacy build/test environment locally.)

Examples before and after:

    >>> [_ for _ in nlp(u'Sam, my brother, arrived to the house.').noun_chunks]
    # Currently
    [Sam, the house]
    # After adding appos
    [Sam, my brother, the house]

    >>> [_ for _ in nlp(u'Whisk together the cumin, chili powder, and salt.').noun_chunks]
    # Currently
    [Whisk]
    # After adding appos
    [Whisk, the cumin, chili powder, salt]

### PR DESCRIPTION
**Pull request by IamJeffG**
Capture more noun chunks, specifically appositional modifiers and indirect objects.

Closes #1226 

## Description

I added two tests and ran `py.test spacy/tests/parser/test_noun_chunks.py`. (Please inform me if the new tests would be better to go in a file `test_issue1226.py`)

## Types of changes
- [ ] **Bug fix** (non-breaking change fixing an issue)
- [x] **New feature** (non-breaking change adding functionality to spaCy) 
    * Improves performance
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:
- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by honnibal** [comment]
Great patch! I forgot about this problem from #1226. Thanks!

**Comment by IamJeffG** [comment]
@honnibal Did you intend to close this without merging?

**Comment by IamJeffG** [comment]
@honnibal Did you intend to close this PR without merging?  Not sure if we can still merge from a closed PR, or if I need to open a new PR to get it onto master.

**Comment by honnibal** [comment]
Argh. Yes, thanks I did mean to merge this -- misclick...

**Pull request merged**
