### PR TITLE
[loggers] Wandb: Added entity option 

### PR DESCRIPTION
**Pull request by filipematos95**
enhancement -> In the loggers: Added entity option as a config option to be able to log into a wandb team directly.

### CODE REVIEW

**Comment by ines** [comment]
Thanks! Can the `entity_name` be `None` as the default? What does the `wandb.init` call expect here?

The way it's currently set up, `entity_name` would become a required config value, which is unideal and probably not what we want. We might also consider making this `v3` of the function, since it'd otherwise require users to run `fill-config` to include the default for `entity_name` in their configs.

**Comment by svlandeg** [comment]
(maintenance note: I'll mark this as WIP until the above comments are addressed/discussed further)

**Comment by svlandeg** [comment]
I'll go ahead and close this for now, as this hasn't been followed up on, and we'll probably be refactoring the logging functionality in the near future.

**Comment by svlandeg** [comment]
Final note: this has been included in https://github.com/explosion/spaCy/pull/9202

**Pull request closed without merging**
