### PR TITLE
Print a warning when multiprocessing is used on a GPU

### PR DESCRIPTION
**Pull request by danieldk**
## Description

As reported in #5507, a confusing exception is thrown when
multiprocessing is used with a GPU model and the `fork` multiprocessing
start method:

cupy.cuda.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error

This change checks whether one of the models uses the GPU when
multiprocessing is used. If so, raise a friendly error message.

Even though multiprocessing can work on a GPU with the `spawn` method,
it quickly runs the GPU out-of-memory on real-world data. Also,
multiprocessing on a single GPU typically does not provide large
performance gains.

### Types of change

Usability improvement.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by danieldk** [comment]
> Do we need this on `develop` or can it just go to `master`? If this wasn't working before anyway, I don't think it's breaking?

I wasn't too sure about this, since technically multiprocessing did work with the `spawn` method before.

**Comment by adrianeboyd** [comment]
I would be more inclined to warn than to try to forbid this.

**Comment by adrianeboyd** [comment]
(Without adding a hack to the website, updating the compatibility table causes the website models page to try to v3.2.0 models that haven't been published yet.)

**Comment by danieldk** [comment]
> It will deadlock in the CI with fork without `torch.set_num_threads(1)`.

Luckily did not happen yet, but I did this anyway for safety.

**Comment by svlandeg** [comment]
@danieldk : could you merge in the latest `master` and try running the GPU tests again?

**Pull request merged**
