### PR TITLE
Remove two attributes marked for removal in 3.1

### PR DESCRIPTION
**Pull request by polm**
## Description

Two attributes in `tokenizer.pxd` were marked for removal in 3.1 but left in. This just removes them. They were no longer in use anywhere.

### Types of change

Minor cleanup.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Careful here: This will change the struct size of the tokenizer, and so will force recompilation of it and anything that cimports it. So we definitely couldn't make this change in a patch release.

**Comment by adrianeboyd** [comment]
I thought that our policy was that we could make changes like this across minor versions. Do you want to handle this differently in the future?

**Comment by honnibal** [comment]
Yes, we can make changes like this across minor versions. However, if there's little to no inconvenience to retaining the object size, it seems reasonable to do that. I see it as a trade-off.

It's fine if you decide "nah let's just remove them". I did want to point out the object size issue though, because it's not at all intuitive, and the CI doesn't really show the problem.

I definitely wouldn't suggest a strict policy of never changing the object sizes in minor versions, that would be really difficult.

**Comment by adrianeboyd** [comment]
Okay, I agree that there's no real harm in waiting for v4, but we'll probably forget again...

**Comment by polm** [comment]
I would be in favor of removing this sooner rather than later. Even observing semver, the more we put it off / less often we make changes like this the harder it becomes to make them and the more trouble we cause when we do change it (since downstream users are less used to it). Additionally, we removed members like this on a minor version before but as far as I'm aware the only negative side effects were with third-party libs doing something odd with serialization, and that may have been unrelated (#8264).

Separately from that, since it seems like `data_dir` in the Vocab is unused, that's another C member that could need removing. Should I add that to this PR?

**Comment by adrianeboyd** [comment]
It does cause some minor issues for things like my `custom-cython-tokenizer` because there's no way to build a v3-compatible wheel.

**Comment by polm** [comment]
OK, I think for now the solution is to close this, mark unused fields in source (with `TODO` or something), and remove on a major change.

**Comment by svlandeg** [comment]
Actually, I thought the consensus was to rename them from now (see Matt's comment earlier). That will ensure they aren't getting used anymore, up until the point we do decide to remove them when the struct needs other changes.

**Comment by polm** [comment]
Ah OK, I misremembered. 

I'll go ahead and add `data_dir`, since it's a similar case.

**Comment by polm** [comment]
OK, I renamed `data_dir` to `_unused_object`. Wasn't sure if I could safely remove it from pickle-related code.

**Review by svlandeg — APPROVED** [review]
Agreed that this is probably safest!

**Pull request merged**
