### PR TITLE
Update Indonesian model

### PR DESCRIPTION
**Pull request by aongko**
## Description
Update Indonesian model

### Types of change
Enhancement

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks for this!

I can't review it in detail myself, so I'll leave it open for maybe a week in case someone else wants to comment. If there's no feedback, we'll go ahead and merge :). Thanks again for your help!

**Comment by geovedi** [comment]
@honnibal yes, please leave it open. i’ll find time this week to test.

**Comment by geovedi** [comment]
@honnibal, looks good for me! 👍

@aongko, thank you for your contribution!

**Comment by fiantinangon** [comment]
why i can find this model on https://spacy.io/models ?

**Pull request merged**
