### PR TITLE
Clean up of char classes, few tokenizer fixes and faster default French tokenizer

### PR DESCRIPTION
**Pull request by svlandeg**
## Description
This PR builds further upon PR https://github.com/explosion/spaCy/pull/3218 and finalizes Issue #1642. Further, it address Issue #3242.

- Split out the huge unicode ranges to allow using `LATIN_BASIC` or `LATIN_LOWER` instead of the large `ALPHA` classes. Note that for some classes, `upper+lower != all` because some unicode characters are a combination of both upper and lower letters and thus only included in the larger group (eg: `_latin_extendedB`)
- For French, removed the large `_tokenizer_exceptions_list.py` from the default model. This also means that `test_issue852` needs to be skipped.

### Small issues

- Added unit test for Issue #2656 (works)
- Added unit test for Issue #3002 (works)
- Removed xfail for Issue #2179 previously fixed by @honnibal 
- Fixed Issue #2822 by adding an Italian exception for `po'` + unit test
- Fixed Issue #2926 by allowing a number right before the infix `/` + unit test
- Added failing unit test for Issue #1235 (can not be fixed without variable-width look-behind)
- Added failing unit test for Issue #2070 (created partial fix, but can not be fully fixed without iterative looping between prefix/suffix and infix)
- Adjusted the documentation on `char_classes.py` in `adding-languages.md` to remove the reference to the  `regex` lib

### Types of change
Small enhancements

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Thanks, this looks super good! 

I can't really make sense of the test failures 🤔 *Something* seems to segfault *somewhere* (where it happens in the tests usually isn't indicative of what actually causes it) and I'm not even 100% sure it's related to your changes?

**Comment by svlandeg** [comment]
Yea, I'm pretty confused too. I'm not sure what could cause this, it's a sort of compiler error?

The only issue I had on my local system when compiling this branch, was that I had some outdated `.cpp` files (`matcher.cp` & `pipeline.cp`) that were moved to a subfolder in one of your recent commits. When trying to recompile from source, I got errors because it was still looking for the corresponding `.pyx` files in the old directories. Deleting those old `.cpp` files fixed that.

But I don't see how this could be a similar issue, as your commits did succeed on the tests before...

**Comment by svlandeg** [comment]
Triggering the tests again with a new commit gives slightly different errors, including

> *** Error in `python': free(): invalid next size (fast): 0x00000000064d5b20 ***

Which seems to point to a memory error. I can't reproduce on my own system though, everything just runs...

**Comment by ines** [comment]
Ok, so I just checked and this seems to be a problem on `develop` that's existed before your PR. It failed in a similar way before that, I just didn't notice.

There's definitely *something* wrong in the matcher, because I ended up with a weird segfault in a test the other day:

https://github.com/explosion/spaCy/blob/3b667787a932efdf2179bb8eb8a1654517e9a3e6/spacy/tests/regression/test_issue1971.py#L53-L67

The really frustrating and confusing thing here is that there's nothing wrong with the assertion it fails on – but *somewhere* previously, there's some memory corruption, so at some point down the line, possibly totally unrelated, it's trying to access something that's not there.

> Deleting those old `.cpp` files fixed that.

Yeah, unfortunately, manually deleting all `.cpp` and `.so` files is sometimes the only good solution.

**Comment by ines** [comment]
Ok, confirmed that the matcher was causing the segfaults. Finally merging 👍

**Pull request merged**
