### PR TITLE
Add cuda101 and cuda102 options to setup

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Add cuda101 and cuda102 options to setup

### Types of change

Enhancement?

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by DROMZEE** [comment]
I have the WARNING

> spacy 2.2.4 does not provide the extra '102'

after this command

> pip install -U spacy[cuda102]

**Comment by adrianeboyd** [comment]
v2.2.4 was released before this change was added. Installing with `pip install spacy[cuda102]` will be supported starting in the next release (most likely v2.3.0).

In the meanwhile, you can install `cupy-cuda102` directly and it should be detected automatically by spacy.

**Comment by MarveM** [comment]
Hi! :) I am currently having the same issue, and have installed copy-cuda101 independently. But I still get the same error "space 2.2.4 does not provide the extra cuda101". With all other requirements already satisfied. So it doesn't seem to auto detect my copy installation? Any way I can force it to?

**Comment by adrianeboyd** [comment]
You don't need to install cupy with the extra option. You can just install them separately and spacy will detect cupy if it's installed.

```
pip install spacy
pip install cupy-cuda101
```

You just need to call `spacy.require_gpu()` to switch to the GPU. If it can't enable it (because there's a problem with your CUDA or cupy setup), you'll see an error.

**Comment by MarveM** [comment]
Thanks for your quick reply! Sorry for misunderstanding. spacy.require_gpu() still failed after the cup-cuda101 install! But it must be a local problem then.

**Pull request merged**
