### PR TITLE
nligraphspacy module - knowledge graph on english sentences using spacy

### PR DESCRIPTION
**Pull request by Vishnunkumar**
# NLI Graph Spacy in English

## Description
Made changes to eng_spacysentiment and added new module nligraphspacy

### Types of change
- updated Twitter profile for eng_spacysentiment
- added new module nligraphspacy - which gives entities in the form of source and target nodes along with the relational edges

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all the required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
Thanks for the PR, we'll give this a review and get back to you!

**Comment by Vishnunkumar** [comment]
Hi team,

I have made changes and added a new library 'spacyspellcheck' which uses inbuilt spacy vocab and Levenshtein distance to get the misspelt words and modify them with possible corrected words. with regards to NLI Spacy graph, I'll create a PR later

**Comment by victorialslocum** [comment]
Hi @Vishnunkumar, 

This looks like a different project than the first one, and the information you provided in the PR has not changed. Can you clarify what this PR is trying to add?

**Comment by Vishnunkumar** [comment]
Hi, 

There is some confusion here I guess, I'll move this PR to drafts and will initiate a new one as per.

**Pull request closed without merging**
