### PR TITLE
Span richcmp fix

### PR DESCRIPTION
**Pull request by nrodnova**
When sorting Spans using just `sorted()` method and relying on Span to handle it, it sorts only on `Span.start` which makes spans that start with the same token to be in random order (or, rather, the original one). It should take the Span's length into consideration as well. Per @adrianeboyd's suggestion, I added comparison based on all `Span` attributes.

The detailed description is here:
https://github.com/explosion/spaCy/issues/9696

## Description

I made this update a while ago and somehow forgot to do a PR for it.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
Thanks for another useful PR! The implementation looks good to me. While there's some repetition, I don't see how that can be avoided while keeping the same efficiency. The tests are quite elaborate as well, which is great, and I don't suspect they'd take much time.

I'll just leave this PR open for now to allow Adriane to have a look as well (she's offline this week).

**Comment by adrianeboyd** [comment]
The tests are great here. I think the whole method would be easier to maintain if all the ops compared the same tuples (ordered in the same way for efficiency) for the comparisons, so something like this:

```python
        self_tuple = (self.c.start_char, self.c.end_char, self.c.label, self.c.kb_id, self.doc)
        other_tuple = (other.c.start_char, other.c.end_char, other.c.label, other.c.kb_id, other.doc)
        # <
        if op == 0:
            return self_tuple < other_tuple
        # <=
        elif op == 1:
            return self_tuple <= other_tuple
        # ==
        elif op == 2:
            return self_tuple == other_tuple
        # !=
        elif op == 3:
            return self_tuple != other_tuple
        # >
        elif op == 4:
            return self_tuple > other_tuple
        # >=
        elif op == 5:
            return self_tuple >= other_tuple
```

I gave this a try and the tests all passed. I could have sworn we were already doing this in another similar place (because tuples compare element by element it works the same as the longer fallback version), but I couldn't find it quickly.

**Comment by nrodnova** [comment]
@adrianeboyd I like it, much more readable :)

**Comment by adrianeboyd** [comment]
I think that this should go in `develop` (v3.3) because the behavior will change, but otherwise think this is fine to merge at this point.

**Review by adrianeboyd — APPROVED** [review]

**Comment by svlandeg** [comment]
Thanks again for the PR @nrodnova and to @adrianeboyd for making the code so much nicer 🤩

**Pull request merged**
