### PR TITLE
Remove questionable French stopwords

### PR DESCRIPTION
**Pull request by alexcombessie**
Linked to #6307

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
I'm not sure how exactly we want to move forward with these stop lists in the code base, but I agree with the general gist of this PR, which removes semantically meaningful French words from the stop list.

**Comment by svlandeg** [comment]
Perhaps we could just version them in v3 and put them in a registry so that edits don't break people's code, but just create newer versions? And store the old versions somewhere, like we'll do with older versions of model implementations?

**Comment by alexcombessie** [comment]
@svlandeg it's a good question. Personally, I would favor no versioning and a direct update of the default list. I am not sure it would break anyone's code. All I did was remove meaningful stopwords from the list, so assuming users are automatically filtering, it will just give them more tokens, i.e. more information.

**Comment by adrianeboyd** [comment]
Let us discuss this and get back to you. There are also some more general issues related to versioning, lexical attributes, and serialization.

**Comment by svlandeg** [comment]
I think "breaking code" was phrased badly on my part, but it would change the results of an NLP/ML model run on top of these stop lists. So there is a factor of reproducibility that we need to take into account.

> @svlandeg it's a good question. Personally, I would favor no versioning and a direct update of the default list. I am not sure it would break anyone's code. All I did was remove meaningful stopwords from the list, so assuming users are automatically filtering, it will just give them more tokens, i.e. more information.

**Comment by honnibal** [comment]
Thanks! It's hard for us to judge stop-words, especially in languages we don't speak well, but the change looks reasonable :).

**Pull request merged**
