### PR TITLE
Fix default parameters for load functions (fix #11706)

### LINKED ISSUE #11706: UserWarning W123 printed on console after upgrading to 3.4.2
After upgrading to `3.4.2` I see this warning on the console when a model is loaded. How to fix or silence this?

> spacy/language.py:1895: UserWarning: [W123] Argument disable with value [] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.

## How to reproduce the behaviour
```python
import en_core_web_sm
lang_model = en_core_web_sm.load()
```

## Your Environment

- **spaCy version:** 3.4.2
- **Platform:** macOS-13.0-arm64-arm-64bit
- **Python version:** 3.10.6
- **Pipelines:** en_core_web_md (3.4.1), en_core_web_sm (3.4.1), en_core_web_lg (3.4.1)

### PR DESCRIPTION
**Pull request by polm**
## Description

Some load functions used SimpleFrozenList() directly instead of the _DEFAULT_EMPTY_PIPES parameter. That mostly worked as intended, but the changes in #11459 check for equality using identity, not value, so a warning is incorrectly raised sometimes, as in #11706.

This change just has all the load functions use the singleton value instead.

### Types of change

minor bugfix

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by rmitsch — APPROVED** [review]
Thanks for fixing this! This can be merged, right?

**Comment by adrianeboyd** [comment]
Can you add a test for this? I think the easiest place would be the extra `ca_core_news_sm` tests that are run for one CI instance at the end of the CI steps. You probably have to check a bit to be sure you're detecting (the absence of) the intended warnings, but I think there's at least one test that does something similar.

**Comment by polm** [comment]
The new test fails on OSX with Python 3.8, and this isn't transient. There's an error about trying to load spaCy twice. Maybe this is related to some of the vendored libraries? It probably is a pre-existing error and not tied to this PR.

**Comment by adrianeboyd** [comment]
It's not specific to macos or python 3.8 (probably), it's that the extra tests that involve downloading models are only run for python 3.8.

**Comment by adrianeboyd** [comment]
#11738 cleans up the working directory to address the unrelated warnings that were causing the new CI test to fail.

**Pull request merged**
