### PR TITLE
Website documentation changes Linguistic features, dependency parse

### PR DESCRIPTION
**Pull request by pktippa**
## Description

- [x] Updated table under Navigating Parse tree with new values, see the [ipynb](https://github.com/pktippa/ai-training/blob/master/natural-language-processing/spacy/Linguistic_features.ipynb)
- [x] Pleases update the current codepen from [here](https://codepen.io/pktippa/pen/jZyWom)

Ques: rather than having a static svg content, can we generate this using displacy.js ?

### Types of change
change to the documentation

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Thanks a lot! 👍

> Ques: rather than having a static svg content, can we generate this using displacy.js ?

In theory, yes, but we didn't really want to introduce another dependency, especially one that needs to make requests to a server running the models etc. In general, we're trying to keep the website as static as possible. There's [this Jade mixin](https://gist.github.com/ines/b53926f0ab50c135338c31ff2b7f6a00) I made for displaCy which we could use instead of the CodePens. I think the main reason I used the copy-pasted markup is to show examples that look exactly like the ones created by the built-in `displacy` module. But maybe this was a bad idea, I'm not sure!

**Comment by pktippa** [comment]
> In general, we're trying to keep the website as static as possible.
I agree with this.

> There's this Jade mixin I made for displaCy which we could use instead of the CodePens.
Jade mixin is good 👍 
I think we can still continue to use CodePens, in the JS section, we can add the JS file which we are using in [demos displacy](https://demos.explosion.ai/displacy/) CodePen (another idea making the displacy.js node module browserify and give the parsed JSON data to generate SVG?) and give the sentence as input and get the rendered svg as output, so that it will be consistent.

**Comment by pktippa** [comment]
Please verify and merge, get the svg from my codepen and update the same on explosion codepen.

**Comment by ines** [comment]
Thanks, updated and will push the updates to the website in a bit! 👍

**Pull request merged**
