### PR TITLE
Update call to `mkdir()` to create the parents

### PR DESCRIPTION
**Pull request by retnuh**
- Update the call to `output_dir.mkdir()` to also create the parents if needed

## Description

Very minor enhancement to hopefully save someone else the pain of half an hour training only to have it bomb out when saving :(

### CODE REVIEW

**Comment by retnuh** [comment]
Surely setting a boolean flag doesn't require a licensing agreement to be signed?

**Comment by honnibal** [comment]
I don't prefer this change actually. If you typo the directory you want to output to, you can end up with things in a weird place. I think it's more reasonable to raise an error if the parent directory is not found.

All pull requests to the library do need the CLA to be signed, even for minor changes. Otherwise we end up in a situation where the rights to the code are unclear, due to an accumulation of small changes from lots of people.

**Comment by retnuh** [comment]
How about checking/making the directory _before_ the training cycle?  It
sucks to spend an hour training a model, expecting the directory to be made
for you, only to have to explode at the very end.

I don't have time to read through the agreement right now, but if you're
amenable to the above idea, I'd be happy to change the PR.

H

**Comment by retnuh** [comment]
the call to `mkdir()` will raise the following:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/foo/bar/bazz/spoo/asdf'
```

I can wrap that with a value error if you like, which would look something like this:

```
ValueError: Can't create output directory /tmp/foo/bar/bazz/spoo/asdf: [Errno 2] No such file or directory: '/tmp/foo/bar/bazz/spoo/asdf'
```

**Comment by honnibal** [comment]
Thanks! Looks good.

**Pull request merged**
