### PR TITLE
Set vectors.name when updating meta.json during training

### LINKED ISSUE #3093: pretrained_vectors meta written inconsistently by CLI
## How to reproduce the behaviour

I would like to build a new model more or less from scratch, using word vectors trained elsewhere:

```
spacy init-model nb path/to/model-with-vectors --vectors-loc input-vectors.txt  [...]
spacy train --vectors path/to/model-with-vectors [...]
```

This works well. But when I try to `spacy.load()` a trained model, it fails with:

`OSError: [E050] Can't find model 'nb_model.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory. `

If I manually remove `"pretrained_vectors": "nb_model.vectors"` from `{ner,tagger,parser}/cfg`, the model appears to work as expected.

<details>
  <summary>Full stack trace</summary>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/util.py", line 116, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/language.py", line 643, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 643, in spacy.pipeline.Tagger.from_disk
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 625, in spacy.pipeline.Tagger.from_disk.load_model
  File "pipeline.pyx", line 535, in spacy.pipeline.Tagger.Model
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/_ml.py", line 447, in build_tagger_model
    pretrained_vectors=pretrained_vectors)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/_ml.py", line 278, in Tok2Vec
    glove = StaticVectors(pretrained_vectors, width, column=cols.index(ID))
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/thinc/neural/_classes/static_vectors.py", line 41, in __init__
    vectors = self.get_vectors()
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/thinc/neural/_classes/static_vectors.py", line 52, in get_vectors
    return get_vectors(self.ops, self.lang)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/thinc/extra/load_nlp.py", line 19, in get_vectors
    nlp = get_spacy(lang)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/thinc/extra/load_nlp.py", line 11, in get_spacy
    SPACY_MODELS[lang] = spacy.load(lang, **kwargs)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/ubuntu/src/spacy-nb/.venv/lib/python3.6/site-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'nb_model.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
</details>

## Info about spaCy

* **spaCy version:** 2.1.0a4
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** de, fr

### PR DESCRIPTION
**Pull request by jarib**
## Description

This fixes #3093 for `spacy train`. Still need to check if it fixes `spacy package` for #3067, so it's a WIP.

### Types of change

Bug fix

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Thanks, this was quick! (And ignore the bot 😛)

>  Still need to check if it fixes `spacy package`

I think the `package` command generates the meta separately – so this might have to be adjusted in `generate_meta` [here](https://github.com/explosion/spaCy/blob/develop/spacy/cli/package.py#L101).

**Comment by ines** [comment]
Looks good – merging! 👍

**Comment by jarib** [comment]
I've added `vectors.name` to `spacy package`'s meta generation and tested that it successfully packages a model with vectors.

A future improvement could be to reduce the duplication by making the model meta data into a class that adds some validation.

**Comment by rbhambriiit** [comment]
Just hit the issue in 2.0.18

One of the smallest pull request for sure :D

**Pull request merged**
