### PR TITLE
Speed up the StateC::L feature function

### PR DESCRIPTION
**Pull request by danieldk**
## Description

`StateC::L` gets the n-th most-recent left-arc with a particular head.

Before this change, `StateC::L` would construct a vector of all left-arcs
with the given head and then pick the n-th most recent from that vector.
Since the number of left-arcs strongly correlates with the doc length
and the feature is constructed for every transition, this can make
transition-parsing quadratic.

With this change `StateC::L`:

- Searches left-arcs backwards.
- Stops early when the n-th matching transition is found.
- Does not construct a vector (reducing memory pressure).

This change doesn't avoid the linear search when the transition that is
queried does not occur in the left-arcs. Regardless, performance
improves quite a bit with very long docs (benchmarked by repeating
a Wikipedia paragraph N times):

Before:

```
   N  Time

 400   3.3
 800   5.4
1600  11.6
3200  30.7
```

After:

```
   N  Time

 400   3.2
 800   5.0
1600   9.5
3200  23.2
```

We can probably do better with more tailored data structures, but I
first wanted to make a low-impact PR.

Found while investigating #9858.

### Types of change

Performance improvement.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ofirnk** [comment]
Looks sound to me.
May I suggest continuing the N in the benchmarks a bit further/more resolutions? 
So it could be apparent if we're really linear here after the fix

**Comment by danieldk** [comment]
> Looks sound to me.
> May I suggest continuing the N in the benchmarks a bit further/more resolutions?
> So it could be apparent if we're really linear here after the fix

I'll check how far I can push it, but with `N = 6400` I went over the maximum doc size.

**Comment by honnibal** [comment]
Yep looks solid 👍

**Review by honnibal — APPROVED** [review]

**Comment by danieldk** [comment]
Forgot to add:

> So it could be apparent if we're really linear here after the fix

It should not yet be linear in this aspect, because this doesn't improve the search when there are not enough left-arcs with the given head. But I wanted to make a PR that doesn't change any data structures first, that can be merged safely in the `main` branch.

I'll do a PR that improves this for all cases (but probably requires some data structure changes next).

**Comment by ofirnk** [comment]
> Forgot to add:
> 
> > So it could be apparent if we're really linear here after the fix
> 
> It should not yet be linear in this aspect, because this doesn't improve the search when there are not enough left-arcs with the given head. But I wanted to make a PR that doesn't change any data structures first, that can be merged safely in the `main` branch.
> 
> I'll do a PR that improves this for all cases (but probably requires some data structure changes) next.

Yes, I meant that the fix actually linearizes what it should.

In more general note - maybe a long document benchmark should be introduced to the test suite?
Something in similar form to the original issue I posted. It should add 3-5 minutes to the test suite, not more.
( I took a real document and truncated it. Not multiplied a paragraph)

We can move discussion to the original issue or any other place suitable, of course.

And I appreciate a lot the effort here 👏

**Comment by danieldk** [comment]
> Yes, I meant that the fix actually linearizes what it should.

Unfortunately, it doesn't because there are many heads that do not have the given index.

At any rate, I have made a refactor of the state representation that does scale linearly (also with much larger sizes). I have to do some more cleanup, but will probably do a PR tomorrow or Friday.

> In more general note - maybe a long document benchmark should be introduced to the test suite?

It would definitely nice to automatically detect such regressions.

**Comment by ofirnk** [comment]
Just saw the release, thanks!

**Comment by visaals** [comment]
@danieldk What was the size in bytes of the Wikipedia paragraph used in this benchmark (`N=1`)? I'm trying to figure out the optimal size to send to `nlp.pipe([chunks])`, thank you!

**Comment by danieldk** [comment]
This is the test text for N=1:

```Ursa Minor (Little Bear) is a constellation in the northern sky. In North America, it is also known as the Little Dipper since its seven main stars appear to form a ladle shape (diagram pictured).```

(From Wikipedia)

**Pull request merged**
