### PR TITLE
Drop support for EOL Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
## Description

Fixes https://github.com/explosion/spaCy/issues/1618.

Drop support for EOL Python 2.6 and 3.3, which also means set literals may be used. 

### Types of change

I think a bug fix.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks for this! Agree with updating the docs and dropping declared support for 2.6 and 3.3. However I don't think switching to set literals is of immediate benefit.

I mean, the code's been working on 2.6 right? So why go out of our way to break it? We don't want to take trouble to support these old versions, but if the code happens to work on them, that's nice.

**Comment by hugovk** [comment]
Well, we all as a community benefit if people move off 2.6, see the links below, but, sure, I can revert that commit when I'm back at a keyboard.

https://snarky.ca/stop-using-python-2-6/
http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by honnibal** [comment]
@hugovk Thanks, revert when you can and then I'll merge.

I quite disagree with the philosophy in that post. It's not a kindness to break code that would otherwise work in some environment, to "helpfully" discourage people from using that environment.

**Comment by hugovk** [comment]
@honnibal Done!

**Comment by honnibal** [comment]
Thanks!

**Pull request merged**
