### PR TITLE
Sync `develop` with `master`

### PR DESCRIPTION
**Pull request by shadeMe**
## Description

Sync branches to aid #11344, which depends on #11312 (to fix test breakage).

A follow-up PR will merge `develop` into `v4`.

### Types of change

Chore

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
I think `master` was just synced to `develop`, so it would be better to do `master` -> `develop` + `develop`->`v4` (otherwise you end up having to do 3 PRs instead of 2, as I did unintentionally a few weeks ago).

**Comment by svlandeg** [comment]
Ah, good point Adriane, but it looks like `develop` is again one commit behind `master` 😭

**Comment by shadeMe** [comment]
Oh, I missed the suggestion to open new PRs. Closing this.

**Comment by adrianeboyd** [comment]
Usually we do this by merging into branches in forks instead of working directly with the main repo branches. It spares some of the weird interactions with main repo branches once you get into situations where the merge is not trivial.

**Pull request closed without merging**
