### PR TITLE
Updated Contributor Agreement

### PR DESCRIPTION
**Pull request by yuukos**
Hello. 
I'm so sorry <(_ _)>, but I have to change my contributor agreement. I have changed 'individual person' to 'developer of company'. I hope that it is not a problem to change.

Changes:
- updated contributor agreement
- added comments about company

## Types of changes

- [ ] **Bug fix** (non-breaking change fixing an issue)
- [ ] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:

- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by honnibal** [comment]
No problem re the contibutor agreement!

I'm a bit worried about the way the comments are written, though. As time goes on, I'm sure other people will contribute to the files. We don't want every file to track the names of who changed it --- we have the commit log for that :).

I think the attribution statement might also be misinterpreted at some point. Some companies have to fill out very bureaucratic compliance statements, keeping track of who issued them a license to use all the code they're using. This is one of the big advantages of the contributor agreement --- there's a single licensor (us), who can be held responsible.

**Comment by yuukos** [comment]
Thank you for understanding.

Can you suggest another way to mention our company? It is really important for us.

**Comment by ines** [comment]
When we release a new version of spaCy, we always mention everyone who's contributed to the update in the release notes – [see here](https://github.com/explosion/spaCy/releases) for examples. Instead of just your username, we could list you as "@yuukos (Expasoft Ltd.)". If you contribute Russian to both v1.x and v2.0, we'll obviously list you on both release notes.

Another option would be that we revert the Russian PR and you re-submit it with a company GitHub account. This way, when people look at the log, the updates and who's contributed, it's more obvious that it was your company and not just "some guy" 😉

**Comment by honnibal** [comment]
Closing this, as either way the solution will be in another PR. I hope we can add the Russian support soon.

**Pull request closed without merging**
