### PR TITLE
prevent zero-length mem alloc

### PR DESCRIPTION
**Pull request by svlandeg**
Following the PR #4423, I went through the entire code base to locate other places where we might be allocating zero-length memory. These should be prevented or flagged to ensure we don't run into more flaky behaviour in the future.

## TODO
Requires detailed review by @ines or @honnibal, as for some of these functions I'm not that familiar with the intrinsic working of the code. 
* Especially the changes to initializing **GoldParse**. The GH comparison is confusing, but I really only moved code + added an `if` statement.
* Also pretty unsure about the `_save_cached` function in **`tokenizer.pyx`**. Is it OK to just abort the whole thing if n `<= 0` ?
* In other cases I used `assert` when the normal flow should not hit a zero-length case. My reasoning is that these are not user-triggered cases, but programming errors.

~~I would suggest to not merge this immediately, to isolate its potential effects from PR #4423. But wanted to get this out so we don't forget.~~ I think this is fine now !

### Types of change
bug prevention !

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
It does feel like this should be something that gets fixed in cymem?

I wonder whether it's my `memset` that causes this. Or maybe it's just that `PyMem_Malloc` doesn't guarantee that 0 allocations return NULL...

**Comment by svlandeg** [comment]
I was going through the docs earlier, and it looks like returning non-NULL is actually the intended behaviour. It should only return NULL when the action fails, and it'll never fail to allocate no bytes...

**Comment by honnibal** [comment]
Oh man. I see.

I think returning NULL from `cymem.Pool.alloc` is less error prone?

**Comment by svlandeg** [comment]
Oh, ofcourse! I temporarily forgot `cymem` is also from Explosion :-)
I'll do that and rework this PR.

**Comment by svlandeg** [comment]
@honnibal : So fixing this in `cymem` makes sense, but I still think we need to make the code in spaCy robust to this too. If we have `cymem.Pool.alloc` return `NULL`, spaCy code will throw an exception when running code like this: https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L603. The exception is kind of ugly "returned NULL without setting an error", so we might as well just throw a ValueException in `cymem.Pool.alloc` which mentions specifically the zero-length problem. 

Actually, by making it throw this error I found one more spot in the code base where it was allocating zero length for `predicate_cache` in the `matcher` (see commit before this comment). 

So I think we need to have both this PR + the change to `cymem` that will automatically flag problematic `alloc`'s in the future.

**Comment by honnibal** [comment]
Wow, I didn't realise I'd typed `cymem.alloc` as `except NULL`. So yeah definitely can't return NULL for empty pointers.

I guess I really forgot how that code worked, and just assumed I knew instead of checking...So yeah we do need to fix this in spaCy. I'm not sure we should raise an error in cymem for zero length --- it should work mostly like malloc and calloc, where you can indeed allocate a zero size pointer. It's up to the calling code to handle that correctly.

So I think the solution is to stop checking pointers for NULL, thinking that means the entry is empty. We just need to look at the lengths.

**Comment by honnibal** [comment]
Hmm okay.

Let's make it an option in Cymem, disabled by default? Cymem does actually have other users, so I'm nervous about breaking their stuff.

I think this will change the size of `Pool` again though :(. That always sucks...It means we have to increment the major version number, and then roll out versions of Preshed and Thinc.

**Comment by svlandeg** [comment]
Ok, the optional flag sounds like a good idea!

**Comment by svlandeg** [comment]
@honnibal : something like [this](https://github.com/explosion/cymem/pull/15/commits/db9dfacd8bf76cdd17be95e08108ae94f2915ab6)? 

Do we then change all the calls to `Pool()` to `Pool(error_alloc_zero=util.env_opt("error_alloc_zero", True))` (or too verbose ?)

I just tested it on the old code (before this PR, i.e. on master), creating a  `GoldParse` with an empty doc would throw an error, unless you set `os.environ["SPACY_ERROR_ALLOC_ZERO"] = "0"`. In/after this PR, neither settings would throw an error because now the code prevents zero-length allocation up-front. But by setting `error_alloc_zero` by default to `True` (in spaCy) we should prevent future errors. In cymem it's set to `False` by default, not to break other's code.

**Comment by honnibal** [comment]
@svlandeg Hmm. I'll keep thinking about this -- I'm kind of nervous about the changes to `cymem.Pool`, and I feel like the API isn't great, as you're suggesting.

Maybe we should just have a global in `cymem.cymem`? We really only need to set it during development to debug, to make sure we don't have one of these allocations.

**Comment by svlandeg** [comment]
Or maybe we just throw a warning?

**Comment by honnibal** [comment]
Throwing a warning by default can also lead to a lot of spam. Maybe a global setting, and if true, warn?

**Comment by svlandeg** [comment]
Ok, I see your point. To be fair, once you start googling, you can find plenty of cases where people ran into this, and several blogposts warning of this kind of behaviour from malloc, we certainly weren't the only ones who got bit by this ;-)

**Comment by svlandeg** [comment]
Ok, see https://github.com/explosion/cymem/pull/15.

This now works on spaCy's master branch:

```
    cymem.WARN_ZERO_ALLOC = True
    doc1 = nlp("")
    with pytest.warns(UserWarning):
        gp1 = GoldParse(doc1)

    cymem.WARN_ZERO_ALLOC = False
    doc2 = nlp("")
    gp2 = GoldParse(doc2)
```

**Comment by honnibal** [comment]
Nice. The `WARN_ZERO_ALLOC` assignment is even backwards compatible, because it will just do nothing on the older cymem version.

And, somewhat comforting to hear it wasn't just me who was holding it wrong :).

**Pull request merged**
