### PR TITLE
Added RONEC to spaCy Universe

### PR DESCRIPTION
**Pull request by avramandrei**
This module offers a named entity recognition model for Romanian Language. The model has been
trained on a  corpus that holds 5127 sentences, annotated with 16 classes. More information about the corpus can be found at https://github.com/dumitrescustefan/ronec/blob/master/README.md.

## Description
We used a script to transform the corpus from CoNLLU-Plus format to spaCy's json. The training has been done using the cli.

### Types of change
We would like to integrate this model with spaCy download interface and easily load with with `spacy.load("ro_ner")`, as described in the sample code.

We have seen [here](https://github.com/explosion/spaCy/issues/2935) that the models must be trained by you. The pipeline of training can be found at https://github.com/dumitrescustefan/ronec/blob/master/spacy/README.md. 

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Oh wow, this is cool! ✨

And just to confirm: the whole corpus is MIT-licensed? If so, we'd definitely be super intested in integrating it into our model training pipeline and publish a `ro_core_web_sm`.

**Comment by avramandrei** [comment]
Yes, it is MIT-licensed: https://github.com/dumitrescustefan/ronec/blob/master/LICENSE

**Comment by avramandrei** [comment]
I have talked with my colleague and it was a misunderstanding from my part. The only trainable part of the corpus is the Named Entity part. The DEP, POS and the others are (partially) generated by another model. We would like to stick with only this part until we come with an update. 

Thank you very much and sorry for the inconvenience.

**Comment by ines** [comment]
@avramandrei Thanks for the clarification. We actually want to retrain all models for v2.2 anyways, so we'll check it out and see if we can get Romanian included.

**Pull request merged**
