### PR TITLE
__init__.py

### PR DESCRIPTION
**Pull request by holubvl3**
## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Hi, please add this commit to the branch in #5826 instead. (`git cherry-pick` should be an easy way to port it over.)

**Comment by holubvl3** [comment]
> Hi, please add this commit to the branch in #5826 instead. (`git cherry-pick` should be an easy way to port it over.)

 @adrianeboyd , I am sorry, I am quite new to GitHub, so please how can I commit it to another branch? 
Thanks.

**Comment by adrianeboyd** [comment]
Clone the github repo locally and find the commit you want to cherry-pick. You can see it above (`e280eb3`) or find it using `git log BRANCH_NAME` like `git log patch-3`. (The whole hash will be longer, you just need the first ~8 digits or so.)

Check out the branch you want to add it to:

```none
git checkout patch-1
```

Then cherry pick:

```none
git cherry-pick e280eb3
```

Then push your local changes back to your github repo, which will automatically be detected in the other PR:

```
git push
```

**Comment by holubvl3** [comment]
@adrianeboyd, thank you, I push it to #5826 .

**Pull request closed without merging**
