### PR TITLE
Add 3rd party licenses file

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Add missing 3rd-party-licenses from #5694.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
👍

This is only going to be a single file, right? If so, can we put this at the root of the repo and avoid the extra `licenses` directory? (Or was there another reason we did this that I don't remember?)

**Comment by adrianeboyd** [comment]
A lot of other packages do something similar and I thought it looked less clutter-y this way (I couldn't think of a shorter filename, but maybe you can?), but it can be anywhere as long the manifest/setup is adjusted accordingly.

**Comment by ines** [comment]
Ah okay! I'm just always wary of adding more directories to the root, especially if they only contain very few files.

What about a file `OTHER_LICENSES` (?) or something like that? Is this too bad? @honnibal  What do you think?

**Comment by honnibal** [comment]
I think a `licenses` directory makes sense? I don't see the problem with having another top-level directory, it looks obviously uninteresting so I don't think it's distracting.

**Comment by ines** [comment]
But are we, realistically, ever going to have more than one file in there? It just seems pointless to me to have a directory for one file?

**Comment by adrianeboyd** [comment]
I think some projects have one file per project / license instead, which may be why other projects had a directory instead. (The next step is to move the scorer license bits here.)

**Comment by honnibal** [comment]
I do think it's cleaner to have the subdirectory, and it'll make it easier going forward. Plus it sorts in a better way.

**Pull request merged**
