### PR TITLE
Add German Stopwords

### PR DESCRIPTION
**Pull request by souravsingh**
Add a list of stopwords for  German Language.

Fixes Issue #364

### CODE REVIEW

**Comment by souravsingh** [comment]
@ines Thanks for the review. The ``a`` and ``b`` in the texts are the result of my mistake. I apologize for that

**Comment by ExplodingCabbage** [comment]
@souravsingh, how did you compile this list? Is it taken from a single source, or multiple? To what extent have you personally tweaked that data by adding words you noticed were missing or removing words you thought were inappropriate? This list looks similar, but not identical, to https://github.com/wgpsutherland/stopwords/blob/master/dist/de.json; I couldn't find any other plausible-looking sources on Google.

(Note that I'm not a project maintainer, just a random guy from the internet, but if I were in @ines's place I'd personally want to know what the source of the data was before merging.)

**Comment by souravsingh** [comment]
@ExplodingCabbage The list was taken from multiple sources. The list was compiled from the website here-http://codingwiththomas.blogspot.in/2012/01/german-stop-words.html and from the stopwords list from Apache Lucene. I had some knowledge of German, so identifying which ones are plausible stopwords wasn't really difficult.

**Comment by ines** [comment]
Thanks for the info! Will merge this now and make a few edits and additions.

Btw, @honnibal and I went over the current state of the language data earlier and it could definitely need some better organisation. Starting with basic formatting, but also more complex stuff – for example, having a global module for emoticons that can be imported across languages (instead of having the same data live in each language).

So I'll be taking this on over the next week or so 😃  English and German will be easy (native German speaker here), but we might post a call for native speakers for the other languages soon, just to have another pair of eyes making sure it's all good.

We have such a great community from all over the world, so we should be able to do this! 💪

**Pull request merged**
