### PR TITLE
Prepare Spanish language for training models, including configuration, rich-UD tag map and tests

### PR DESCRIPTION
**Pull request by dvsrepo**
## Description

This pull request prepares spaCy 1.7.x for training the Spanish models. It adds configuration details, a new tag map extracted from current version of UD_esAncora corpus by combining pos tags and morphology.

Using these changes, we have trained the Spanish models internally, reaching satisfying results:

```Results

    TOK                100.00
    POS                96.70
    UAS                87.34
    LAS                83.51
```
In order to replicate this model, the following steps can be performed:

* Run init https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py using word_freqs, brown clusters, and GloVe vectors (we have them internally and willing to share them).

* Using https://github.com/explosion/spacy-dev-resources/pull/11 convert UD_esAncora to JSON train cli format.

* Run train with new cli.

**Tests:**
We have created the es folder for tests and added basic tests. All existing and new tests pass.

As far as I see, current version of spaCy only performs model tests for en model, we would like to add model tests for testing: sentence segmentation, tagging, parsing, etc. once the model is available.

Testing env:
```
## Info about spaCy

* **spaCy version:** 1.7.3
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:**
```
## Types of changes

- [ ] **Bug fix** (non-breaking change fixing an issue)
- [x] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [ ] **Documentation** (addition to documentation of spaCy)

## Checklist:

- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by magnusburton** [comment]
Hello @dvsrepo! Would love to see a snippet of your training data that you used internally for a brief idea of how my training data should be structured. Been looking for some general guidelines on the docs btw have not found anything as of now. Thanks!

**Comment by dvsrepo** [comment]
Hi @magnusburton:

Basically you need three items for setting up a new language:

* Word freqs from a large raw corpus. We used http://data.statmt.org/ngrams/deduped/ and the word_freqs script in spacy-dev-resources repo. One important thing to note is that your corpus should not be preprocessed (i.e., you need punctuation for example).

* Word vectors. That should be created from a large raw corpus. We used http://data.statmt.org/ngrams/deduped/ and GloVe. This time you can preprocess your corpus (lower case, remove punctuations, etc.)

* Brown clusters. 

With all this three resources, you can use  https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py to setup your language model structure. 

Once you have setup this structure, to train the Tagger and the Parser:

* Find an corpus for your language annotated with universal dependencies. 

* This corpora use the conllu format, which can be converted into spaCy's JSON train format using the `convert` command provided by the spaCy client (https://spacy.io/docs/usage/cli#convert).

* Once you have your UD corpus transformed into JSON, you can use the `train` command provided by the spaCy client (https://spacy.io/docs/usage/cli#train).

Some snippets of our data are:

**word_freqs.txt**

```
6361109	111	Aunque
23598543	111	aunque
10097056	111	claro
193454	111	aro
7711123	111	viene
12812323	111	mal
23414636	111	momento
2014580	111	felicidad
233865	111	repleto
15527	111	eto
235565	111	deliciosos
17259079	111	buena
71155	111	Anímate
37705	111	anímate
33155	111	cuéntanos
2389171	111	cuál
961576	111	típico
```

**clusters.data**

```
0000	Vestigial	1
0000	Vesturland	1
0000	Veyreau	1
0000	Veynes	1
0000	Vexilografía	1
0000	Vetrigne	1
0000	Vetónica	1
0000	Asunden	1
0000	Villalambrús	1
0000	Vichuquén	1
0000	Vichtis	1
0000	Vichigasta	1
0000	VAAH	1
0000	Viciebsk	1
0000	Vicovaro	1
0000	Villardeveyo	1
0000	Vidala	1
0000	Videoguard	1
0000	Vedás	1
0000	Videocomunicado	1
0000	VideoCrypt	1
```
**vectors.bin** with one word and vector per line (pretty standard format for word2vec, GloVe, etc.

**Comment by ines** [comment]
@dvsrepo Thanks for this great and helpful comment – would you mind if we reuse some of this in the docs? I think this would be useful to a lot of other users as well.

Also, one small addition:
> With all this three resources, you can use https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py to setup your language model structure.

There's now also a [`model` command](https://spacy.io/docs/usage/cli#model) – basically an improved version of that script. (The version in v1.8.0 comes with a small bug that places the vectors in the wrong directory, though – but his has since been [fixed on master](https://github.com/explosion/spaCy/blob/master/spacy/cli/model.py).)

**Comment by magnusburton** [comment]
@dvsrepo This is great, thank you for the detailed explanation. Gotta get working on the Swedish model now.

**Pull request merged**
