### PR TITLE
JapaneseTokenizer.pipe added

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
## Description
For [spacymoji](https://spacy.io/universe/project/spacymoji)  with `Japanese()`.

### Types of change
To use JapaneseTokenizer.pipe as same as Tokenizer.pipe

## Checklist

- [ ] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Hi, thanks for this PR! Looking at the details, I think it would make more sense to add it to `DummyTokenizer` so it fixes this issue for several languages at once (Chinese, Japanese, Korean, Thai), but then you also have to handle an unimplemented `__call__` method in `DummyTokenizer`. I think you could add:

```
class DummyTokenizer(object):
    def __call__(self, text):
        raise NotImplementedError

    def pipe(self, texts, **kwargs):
        for text in texts:
            yield self(text)

    ...
```

If you wanted you could warn about `n_threads` as in `Tokenizer.pipe`, but I don't think this is a big deal. None of the tokenizers do any batching, and `nlp.pipe()` just calls `nlp.make_doc()`, so you don't notice the missing `tokenizer.pipe()` in most typical use cases.

**Comment by adrianeboyd** [comment]
Thanks, this looks good!

**Comment by KoichiYasuoka** [comment]
Thank you for suggestion, @adrianeboyd , and `Thai()` seems OK now with `spacymoji`.

**Comment by adrianeboyd** [comment]
Don't worry about the python 3.5 test, that's unrelated (and should be fixed by #6522).

**Pull request merged**
