### PR TITLE
Use nlp.pipe in EntityRuler for phrase patterns in add_patterns

### PR DESCRIPTION
**Pull request by kabirkhan**
## Description

The EntityRuler will now use nlp.pipe for all phrase patterns. This can drastically reduce time for adding a large number of phrase patterns. 

### Types of change

Enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Take a look at the discussion in #4119. I don't think that we can make the assumption that if an attribute isn't in `(DEP, POS, TAG, LEMMA)` that `nlp.make_doc()` is sufficient.

**Comment by kabirkhan** [comment]
Sorry, could have found that myself I'm sure. Based on that issue, I've refactored the add_patterns function to use nlp.pipe for add_patterns. 

It gets a 10x-20x speedup from the old function in my tests of 5000-100000 phrase patterns.

It's obviously still faster to disable pipeline components when running add_patterns but that's still extra for the user to remember and non-trivial for loading patterns from disk. I've added some docs explaining this issue in more detail. Not at all attached to my writing so feel free to request changes in that explanation.

**Comment by honnibal** [comment]
@kabirkhan @adrianeboyd Sorry for the lack of attention to this. It looks good to me but I wanted to double check with you both, is it safe to merge now?

**Comment by kabirkhan** [comment]
Not yet, shoot I accidentally pushed a commit to this PR based on this WIP PR: https://github.com/explosion/spaCy/pull/4988. I'll revert that commit here.

**Comment by kabirkhan** [comment]
Ok should be all good now, sorry about that. 

Should be safe to merge

**Pull request merged**
