### PR TITLE
Set version to v3.1.1

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Set version to v3.1.1

### Types of change

?

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
Oh, oops, yes, this would have been nicer than commiting directly to the `master` branch :p

**Comment by adrianeboyd** [comment]
I like to do a final CI run, especially because of the download tests.

**Comment by svlandeg** [comment]
Is this not sufficient? https://dev.azure.com/explosion-ai/Public/_build/results?buildId=13323&view=results

**Comment by adrianeboyd** [comment]
I guess I'd much rather test then commit, especially to `master`.

**Pull request closed without merging**
