### PR TITLE
fix ja leading spaces

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**
Bug fix for `spacy.lang.ja`: exception raised when dtoken.surface starts with " " #5961 

## Description
Change the condition of space after by seeing the surface of the next token.

### Types of change
 a bug fix

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by svlandeg — COMMENTED** [review]
Thanks for such a quick fix! I suggest to have the original case from that issue as a unit test? (and preferably some additional cases as well).

**Comment by hiroshi-matsuda-rit** [comment]
@svlandeg I added a text to NAUGHTY_STRINGS. Is it okay?

**Comment by svlandeg** [comment]
I think so! @adrianeboyd : does this look OK to you?

**Comment by adrianeboyd** [comment]
I think it looks fine!

**Comment by hiroshi-matsuda-rit** [comment]
CI tests done.
How about develop branch?
May I send the same PR to develop?

**Comment by svlandeg** [comment]
There's no need for that, we sync such fixes periodically!

**Pull request merged**
