### PR TITLE
[universe project] create English interpretation project 

### PR DESCRIPTION
**Pull request by lll-lll-lll-lll**
## Description

Created a project that uses Spacy to return the results of English interpretation.
link : https://github.com/lll-lll-lll-lll/sent-pattern
Pre-processing for accurate translation of English into Japanese. 
### Types of change

It's PR is universe project

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by polm** [comment]
Thanks for the submission, this looks like a neat project!

In your code you refer to things like the "first sentence pattern", "fourth sentence pattern", and so on. I'm not familiar with these sentence patterns, are they from a particular book or something?

**Comment by lll-lll-lll-lll** [comment]
Thanks for the reply!

Generally, you can find it in Japanese books on English interpretation

This sentence pattern is a pattern of sentence structure from the core elements of a sentence.
For example, a first sentence pattern means that the subject and verb are the core elements, and the other elements consist of words that produce adjectives and adverbs. In Japanese, 第一文型 is called "first sentence pattern".
There are a total of five such sentence patterns.
So, give it a try and look it up under "英文解釈　文型" It's in Japanese!

**Comment by polm** [comment]
Thank you, that makes things a lot clearer! I was able to find [an academic paper](https://www.intcul.tohoku.ac.jp/ronshu/vol17/12.pdf) in English about the history of the concept in Japan.

The term "sentence patterns" is really general, so for the project description, maybe you could change it to something like this so that it's clear what they refer to?

> This package categorizes English sentences into one of five basic sentence patterns and identifies the subject, verb, object , and other components. The five basic sentence patterns are based on C. T. Onion's "Advanced English Syntax" and are frequently used when teaching English in Japan.

**Comment by lll-lll-lll-lll** [comment]
Oh!!!! Thanks! I'll read that literature.
I have adopted your suggestion.

**Comment by polm** [comment]
Did you forget to push?

**Comment by lll-lll-lll-lll** [comment]
sorry, I forget. now changed and push

**Comment by polm** [comment]
Excellent, thank you!

**Pull request merged**
