### PR TITLE
Black / Flake8 as Pre-Commit hooks

### PR DESCRIPTION
**Pull request by julien-talkair**
## Description
Using the pre-commit framework, installs a git pre-commit hook so that `black` and `flake8` run automatically on modified files when user initiates as `git commit`

### Types of change

New feature for devs.
Documentation change in CONTRIBUTING.md

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
Thanks, really appreciate the repo maintenance help 🙌

We've been thinking about giving pre-commit hooks for formatting a try for a while!

One quick question: Do you happen to know if there's an easy way to configure the settings for `flake8` for the pre-commit hook? Idealy, we would want to only run the most important checks (syntax errors etc.) that we also currently run in the CI:

https://github.com/explosion/spaCy/blob/2fc67e2aeb764760e0e950ffd99c43afddf11825/azure-pipelines.yml#L32

In general, we do want to make sure that the code follows all the rules defined in the `setup.cfg` (e.g. unused variables or imports), but we wouldn't necessarily want to enforce them on each commit. Very clear errors are obviously good, though, because those will always be bugs.

**Comment by julien-talkair** [comment]
@ines it is feasible to give arguments to `flake8` indeed.
I tried with voluntary errors, and `flake8` failed only on those in the list.

On the other hand, since the pre-hook starts with `black`, some of the `flake8` errors will result anyway in an error with `black`. 

Just for conversation, I see that `black` is not used at all on the CI, is that a deliberate choice?
It's a requisite for devs in your [CONTRIBUTING.md](CONTRIBUTING.md).

**Comment by julien-talkair** [comment]
On the other hand, maybe you meant to use [setup.cfg](setup.cfg) as the source for arguments... I have to check that.

**Comment by ines** [comment]
> On the other hand, maybe you meant to use setup.cfg as the source for arguments... I have to check that.

Yes, that's how we do it for our end-to-end linting and it's detected automatically from there. But it's not necessarily something we would want to enforce for everyone – although, it's obviously desired that new code passes all of these linting rules.

> Just for conversation, I see that black is not used at all on the CI, is that a deliberate choice?

Yeah, we were actually just discussing this internally the other day and dedided to not enforce this because it'd otherwise lead to too many problems with user-submitted PRs, especially for users who are newer to Python programming and less familar with using linters and auto-formatters.  

Instead, we opted for an `autoblack` GitHub action that runs once a week and submits a PR: https://github.com/explosion/spaCy/actions/workflows/autoblack.yml (Due to how GitHub tokens work, it's unfortunately not possible to run this automatically for PRs, because those are mostly submitted from forks, which the token doesn't grant permissions to.)

**Comment by julien-talkair** [comment]
@ines
Now flake8 in the pre-commit hook uses `setup.cfg` as a configuration.
I tested manually by adding intentional E266 anti-patterns, it was detected when the  `E266` was removed from the `ignore` line, and `flake8` stayed silent when it was in the `ignore` line.

**Comment by ines** [comment]
Cool, thanks so much for your work on this 🙏 I'll go ahead and merge this and I hope this addition will be helpful to others.

**Pull request merged**
