### PR TITLE
Refactor warnings

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Use `warnings.warn` instead of `logger.warning` everywhere outside of `spacy.training`
* Only show the noisy rule-based lemmatizer warning about missing POS once

### Types of change

Enhancement?

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
DON'T SQUASH!

**Comment by svlandeg** [comment]
Why didn't you cherry-pick to `develop` and then build on top of that? Would be more easy to review and follow what's happening ;-)

**Comment by adrianeboyd** [comment]
Just review the second commit? (I usually try to avoid pushing to `develop` without a separate PR, which seemed like overkill here just for one commit. But I can redo it if you'd really prefer it.)

**Comment by svlandeg** [comment]
Looks fine by me!

**Pull request merged**
