### PR TITLE
`Matcher`: Remove superfluous GIL-acquiring check in `get_is_final`

### PR DESCRIPTION
**Pull request by shadeMe**
## Description
This check incurred a significant performance penalty due to implict interactions between the GIL and Cython ref-counting code.

### Types of change

Bug fix

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
We've already discussed this internally, and this looks good to merge? Was there anything else you wanted to do/experiment with still, Madeesh?

**Comment by shadeMe** [comment]
I was going to flag it as ready as soon as the tests successfully ran to completion, but then the breakage due to the allocations PR happened. 

I'd say that the changes in this PR shouldn't haven't any unforeseen side-effects, so it should be safe to merge. But we could also wait until next week, if we want to err on the side of caution.

**Comment by svlandeg** [comment]
Raising the error there was more about being robust to future bugs, I can't imagine removing that check to cause any bugs by itself, really?

**Comment by shadeMe** [comment]
On second thought, you're right. The change is very unlikely to break anything. I'll mark it as ready :)

**Pull request merged**
