### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by ryndaniels**
(Please do not close or merge this! I want to leave it open for a while to test explosion-bot! 🤖 Thanks!)

### CODE REVIEW

**Comment by ryndaniels** [comment]
@explosion-bot please test-gpu

**Comment by ryndaniels** [comment]
@explosion-bot please test_gpu

**Comment by ryndaniels** [comment]
@explosion-bot please test_gpu

**Comment by adrianeboyd** [comment]
I think it's just the tests. They need an `ops.to_numpy` conversion.

**Comment by svlandeg** [comment]
@explosion-bot please test_gpu

**Pull request closed without merging**
