### PR TITLE
Reduce frequency with which on_match callbacks are called

### PR DESCRIPTION
**Pull request by Ankush-Chander**
## Description
Current matcher implementation makes all callbacks run on all matches. Desired behaviour is each callback(on_match) should be passed patterns linked with that callback only. 
### Changes I made:
1. Group patterns based on matcher and pass all matched patterns to corresponding callback function.
2. Update test case as one matcher should have one call in which it handle all matched patterns.

### Test script used:
```
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Doc
nlp = spacy.load("en_core_web_sm")
Doc.set_extension("suggestions", default=[], force=True)

def on_match_adv(matcher, doc, id, matches):
    print(f"inside on_match_adv")
    print(f"matches: #expected=2, #got={len(matches)}")
    print(f"matches: {[doc[start:end] for _, start, end in matches]}")
    for _, start, end in matches:
        matched_span = doc[start:end]
        startIndex, endIndex = matched_span.start_char, matched_span.end_char
        coveredText = matched_span.text
        errorText = f"adverb-replacement"
        comment = f"Replace '{coveredText}' with '{errorText}'."
        suggestion = {"startIndex": startIndex, "endIndex": endIndex,
                      "coveredText": coveredText, "errorText": errorText,
                      "comment": comment}
        doc._.suggestions.append(suggestion)


def on_match_pron(matcher, doc, id, matches):
    print(f"inside on_match_pron")
    print(f"matches: #expected=1, #got={len(matches)}")
    print(f"matches: {[doc[start:end] for _, start, end in matches]}")
    for _, start, end in matches:
        matched_span = doc[start:end]
        startIndex, endIndex = matched_span.start_char, matched_span.end_char
        coveredText = matched_span[0].text
        errorText = f"pron-replacement"
        suggestion = {"startIndex": startIndex, "endIndex": endIndex,
                      "coveredText": coveredText, "errorText": errorText}
        doc._.suggestions.append(suggestion)


if __name__ == '__main__':
    sentence = "This is just just an example sentence."
    matcher = Matcher(nlp.vocab)
    # handle adverbs
    matcher.add("v1",[[{'POS': 'ADV'}]], on_match=on_match_adv)
    # handle pronouns
    matcher.add("v2", [[{'POS': 'PRON'}]], on_match=on_match_pron)
    doc = nlp(sentence)
    matches = matcher(doc)
    try:
        assert len(doc._.suggestions) == 3
    except Exception as err:
        print(doc._.suggestions)
    print(f"#suggestions expected: 3, got:{len(doc._.suggestions)}")

    # current behaviour:
    #1. calls `on_match_adv` twice once for each adverb occurence, on_match_pron once for single occurence of pronoun
    #2. act on all matched_patterns(3) in each callback
    #3.  final outcome: 9 suggestions (3*3 )
    
    # desired_outcome:
    # 1. should call `on_match_adv` once and handle both adverb occurences in that call
    # 2. should call `on_match_pron` once and handle all pron occurences in that call
    # 3. final outcome: 3 suggestions 2 for adverbs, 1 for pron (1 callback * 2 patterns+ 1 callback *1 matched pattern)

```

### Types of change
It is a bug fix.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Thanks for taking a closer look at this! I see how you're trying to group matches with the same key together to reduce the number of calls to `on_match`, but I think this modifies the design of `on_match` too much.

Currently `on_match` is called once for each match associated with this callback and it is given access to all the matches on the doc, not just the matches for this key. The `i` in `on_match(self, doc, i, matches)` points to the index of that single match in the list of all matches (`matches[i]`). Here's an example from the docs that shows how `on_match` selects the individual match using `i`: https://spacy.io/usage/rule-based-matching#on_match

The idea is that for maximum flexibility, each call to `on_match` has access to basically all the information we have for the `Matcher` and all the matches for this doc. `on_match` can potentially use information from other matches in order to decide how to process an individual match.

I do see that there's no test in the test suite that checks that the right callback is called exactly once with the correct `i` for each corresponding match in the matches, so that is something we could add, which would help make this clearer for developers.

**Comment by Ankush-Chander** [comment]
Hi @adrianeboyd 
Thank you for the clarification. Passing global information makes sense.

I was able to achieve desired outcome by modifing code as follows:
```
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Doc
nlp = spacy.load("en_core_web_sm")
Doc.set_extension("suggestions", default=[], force=True)


def on_match_adv(matcher, doc, id, matches):
    _, start, end = matches[id]
    matched_span = doc[start:end]
    startIndex, endIndex = matched_span.start_char, matched_span.end_char
    coveredText = matched_span.text
    errorText = f"adverb-replacement"
    comment = f"Replace '{coveredText}' with '{errorText}'."
    suggestion = {"startIndex": startIndex, "endIndex": endIndex,
                  "coveredText": coveredText, "errorText": errorText,
                  "comment": comment}
    doc._.suggestions.append(suggestion)


def on_match_pron(matcher, doc, id, matches):
    _, start, end = matches[id]
    matched_span = doc[start:end]
    startIndex, endIndex = matched_span.start_char, matched_span.end_char
    coveredText = matched_span[0].text
    errorText = f"pron-replacement"
    suggestion = {"startIndex": startIndex, "endIndex": endIndex,
                  "coveredText": coveredText, "errorText": errorText}
    doc._.suggestions.append(suggestion)


if __name__ == '__main__':
    sentence = "This is just just an example sentence."
    matcher = Matcher(nlp.vocab)
    # handle adverbs
    matcher.add("v1",[[{'POS': 'ADV'}]], on_match=on_match_adv)
    # handle pronouns
    matcher.add("v2", [[{'POS': 'PRON'}]], on_match=on_match_pron)
    doc = nlp(sentence)
    matches = matcher(doc)
    try:
        assert len(doc._.suggestions) == 3
    except Exception as err:
        print(doc._.suggestions)
    print(f"#suggestions expected: 3, got:{len(doc._.suggestions)}")

```

**Comment by Ankush-Chander** [comment]
I have one more suggestion:
Currently if one of the callbacks raises exception, it causes entire matcher to exit.

Desired outcome is:  
Exception in callback should be handled gracefully and it should allow other callbacks to continue functioning. 

Here"s how I intend to handle it in [matcher.pyx](https://github.com/explosion/spaCy/blob/c223cd7a86f460f3dabb9e7369eef136a653218e/spacy/matcher/matcher.pyx#L318):

```
                try:
                    on_match(self, doc, i, final_matches)
                except Exception as err:                    
                    print("some useful warning specifing key and error trace")
```
Please suggest.

**Comment by adrianeboyd** [comment]
You should be able to handle any exceptions yourself with your own `on_match` methods?

**Comment by Ankush-Chander** [comment]
We have around 7k rules and corresponding  `on_match`. Atleast the   error message should convey which one failed.
And ideally one callback should have nothing to do with the other. 
But I got your point. We can more attention while writing our callbacks.

**Comment by adrianeboyd** [comment]
I'll go ahead and close this PR for now, feel free to start a discussion thread with any related questions.

**Pull request closed without merging**
