### PR TITLE
Add save after `--save-every` batches for `spacy pretrain`

### PR DESCRIPTION
**Pull request by tokestermw**
When using `spacy pretrain`, the model is saved only after every epoch. But each epoch can be very big since `pretrain` is used for language modeling tasks. So I added a `--save-every` option in the CLI to save after every `--save-every` batches.

## Description

To test...

Save this file to `sample_sents.jsonl`

```
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
```

Then run `--save-every 2` when pretraining.

```bash
spacy pretrain sample_sents.jsonl en_core_web_md here -nw 1 -bs 1 -i 10 --save-every 2
```

And it should save the model to the `here/` folder after every 2 batches. The models that are saved during an epoch will have a `.temp` appended to the save name.

At the end the training, you should see these files (`ls here/`):

```bash
config.json     model2.bin      model5.bin      model8.bin
log.jsonl       model2.temp.bin model5.temp.bin model8.temp.bin
model0.bin      model3.bin      model6.bin      model9.bin
model0.temp.bin model3.temp.bin model6.temp.bin model9.temp.bin
model1.bin      model4.bin      model7.bin
model1.temp.bin model4.temp.bin model7.temp.bin
```

### Types of change

This is a new feature to `spacy pretrain`.

🌵 **Unfortunately, I haven't been able to test this because compiling from source is not working (cythonize error).** 

```
Processing matcher.pyx
[Errno 2] No such file or directory: '/Users/mwu/github/spaCy/spacy/matcher.pyx'
Traceback (most recent call last):
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 169, in <module>
    run(args.root)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 158, in run
    process(base, filename, db)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 124, in process
    preserve_cwd(base, process_pyx, root + ".pyx", root + ".cpp")
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 87, in preserve_cwd
    func(*args)
  File "/Users/mwu/github/spaCy/bin/cythonize.py", line 63, in process_pyx
    raise Exception("Cython failed")
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 276, in <module>
    setup_package()
  File "setup.py", line 209, in setup_package
    generate_cython(root, "spacy")
  File "setup.py", line 132, in generate_cython
    raise RuntimeError("Running cythonize failed")
RuntimeError: Running cythonize failed
```

Edit: Fixed! after deleting all `.cpp` files: `find spacy -name "*.cpp" | xargs rm`

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ines** [comment]
>  Unfortunately, I haven't been able to test this because compiling from source is not working (cythonize error).

This looks like you still have some old compiled `.so` or `.cpp` files sitting around in your local directory. So if you delete those, it should compile as expected.

**Comment by honnibal** [comment]
@tokestermw Thanks!

While you're at it, if you wanted to add some resume logic, that would also be great. We couple pickle the optimizer at each checkpoint as well, but even without that, just loading back in the weights is probably fine.

**Comment by tokestermw** [comment]
> While you're at it, if you wanted to add some resume logic, that would also be great. 

I can add another PR 👍 

Though I am trying to load back the trained `Tok2Vec` model by using `_load_pretrained_tok2vec`

```
python - <<-EOF
from pathlib import Path
from spacy.cli.train import _load_pretrained_tok2vec
import spacy
nlp = spacy.load('en_core_web_md');
_load_pretrained_tok2vec(nlp, Path('./here/model0.bin'))
EOF
```

and running into this error 😢 

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/mwu/github/spaCy/spacy/cli/train.py", line 372, in _load_pretrained_tok2vec
    component.tok2vec.from_bytes(weights_data)
  File "/Users/mwu/github/spaCy/venv/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 371, in from_bytes
    dest = getattr(layer, name)
AttributeError: 'FunctionLayer' object has no attribute 'vectors'
```

**Comment by honnibal** [comment]
@tokestermw Did you check that your usage of the `--use-vectors` flag matches up with whether you want to use vectors in the input at runtime? If you want to train for the `md` or `lg` cases, using vectors is good.

**Comment by tokestermw** [comment]
> `nlp = spacy.load('en_core_web_md');`

OK, switching to `en_core_web_sm` gets rid of the error (which makes sense given the missing `vectors` error). It was definitely teh `-uv` (`--use-vectors`) option. I created a table for the results.

| Pretrain | Load pretrained Tok2Vec | Result | 
| --- | --- | --- |
| None | `en_core_web_md` | No `vectors` error |
| None | `en_core_web_sm` | ✅ |
| `-uv` | `en_core_web_md` | ✅ |
| `-uv` | `en_core_web_sm` | Broadcast shape error |

**Comment by tokestermw** [comment]
@honnibal I think this PR is ready! I am planning to add resume logic in another PR.

**Comment by tokestermw** [comment]
Looks like `pretrain` uses `--nr-iter`, so maybe `--nr-save-every`? Though `train` uses `--n-iter` haha

**Comment by tokestermw** [comment]
I've renamed `nr_iter` to `n_iter`, and `save_every` to `n_save_every`, also in the docs (`cli.md`)

**Comment by robertsonwang** [comment]
Reposting here for visibility:

> 👋 There's been a breaking change in train.py for this functionality. Specifically, _load_pretrain_tok2vec now has a base_components argument. This argument is used to check that a pretrained base component is not combined with a pretrained tok2vec layer. I got around the error by setting base_components="" but the proper solution would probably be to pass a base_components argument somewhere in the pretrain call.

**Pull request merged**
