### PR TITLE
Load components dynamically (decrease initial file size for docs)

### PR DESCRIPTION
**Pull request by essenmitsosse**
## Description
Using [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import) to decrease initial file download size, as well as optimize download size for simpler pages, since only the necessary JavaScript is being loaded. The main impact is, that the rendering of code blocks is delayed, but that effect is only noticeable (if at all), because the rest of the page now renders faster.

|                                                                                                                                                                         | [Before<br>(Gatsby)](https://635f4ed7058593000845b404--spacy.netlify.app/) | [Before<br>(Next)](https://63cffc1c705ac900088bb7c6--spacy.netlify.app/) | [After](https://635f4ed7058593000845b404--spacy.netlify.app/)  | After/Before(Next) |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|---------------|--------|---------------------|
| First Load JS shared by all[^0]                                                                                                                                         | 4200kb          | 753kb         | 148kb  | 19%                 |
| Largest `.js` frontpage                                                                                                                                                 | 3900kb          | 2200kb[^4]    | 650kb  | 29%                 |
| Largest `.js` file `/api/architectures`[^1]                                                                                                                             | 3900kb          | 2200kb[^4]    | 225kb  | 10%                 |
| Total download[^2] frontpage                                                                                                                                            | 4400kb          | 2700kb[^4]    | 2200kb | 81%                 |
| Total download[^2] `/api/architectures`                                                                                                                                 | 4400kb          | 2700kb[^4]    | 819kb  | 30%                 |
| [First Contentful Paint](https://developer.chrome.com/docs/lighthouse/performance/first-contentful-paint/?utm_source=lighthouse&utm_medium=devtools)[^3]                | 0.5s            | 0.3s          | 0.3s   |                     |
| [Time to Interactive](https://developer.chrome.com/docs/lighthouse/performance/interactive/?utm_source=lighthouse&utm_medium=devtools)[^3]                              | 1.6s            | 0.6s          | 0.5s   |                     |
| [Speed Index](https://developer.chrome.com/docs/lighthouse/performance/speed-index/)[^3]                                                                                | 0.9s            | 0.6s          | 0.5s   |                     |
| [Total Blocking Time](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-total-blocking-time/?utm_source=lighthouse&utm_medium=devtools)[^3]           | 420ms             | 0ms          | 0ms    |                     |
| [Largest Contentful Paint](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-largest-contentful-paint/?utm_source=lighthouse&utm_medium=devtools)[^3] | 2.2s            | 1.1s          | 0.8s   |                     |
|Lighthouse Performance Score[^5]|~70|95+|98+||

### Types of change
- Performance improvements for docs

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

[^0]: According to the Next build
[^1]: Example of a page with mainly text content
[^2]: including styles, images etc.
[^4]: Previous site was always loading all of the JavaScript, so download size was the same for all pages
[^3]: Frontpage
[^5]: As all Lighthouse values these fluctuate between runs

### CODE REVIEW

**Comment by ines** [comment]
Thanks for the detailed benchmarks overview 💯 One thing I still want to check here: How does this affect the static fallback, e.g. if a user has JavaScript disabled?

**Comment by essenmitsosse** [comment]
Well the code snippets are currently not working without JavaScript enabled anyway. But the old [Gatsby site](https://635f4ed7058593000845b404--spacy.netlify.app/) wasn't working at all without JavaScript. So it doesn't improve on it, but it also doesn't make it worse.

**Comment by ines** [comment]
Yeah, for the quickstart guides etc. it's fine. It'd just be good to have the interactive code snippets fall back to the static rendering if we can do that.

And I'm pretty sure the old site did work without JS if you don't have the service worker installed (which wouldn't install if you first visit the site without JS enabled).

**Comment by ines** [comment]
Not sure what causes this but looking at the deploy preview, it seems the pre-defined CLI command highlights stopped working:

Screenshot 2023-01-25 at 13 19 55

**Comment by essenmitsosse** [comment]
> Not sure what causes this but looking at the deploy preview, it seems the pre-defined CLI command highlights stopped working:

This was solved via #12172, but is not reflected in this PR yet.

**Review by ines — APPROVED** [review]

**Pull request merged**
