### PR TITLE
morphologizer: avoid recreating label tuple for each token

### PR DESCRIPTION
**Pull request by danieldk**
## Description

The `labels` property converts the dictionary key set to a tuple. This property was used for every annotated token, recreating the tuple over and over again.

Construct the tuple once in the set_annotations function and reuse it.

On a Finnish pipeline that I was experimenting with, this results in a speedup of ~15% (~13000 -> ~15000 WPS).

### Types of change

Performance improvement.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Nice! I bet `tagger` and `senter` have the same issue, too.

**Comment by danieldk** [comment]
> Nice! I bet `tagger` and `senter` have the same issue, too. (You probably can't measure the speed difference with `senter`, though.)

Good catch, `Tagger` does. I noticed this one while profiling embedding stuff, I guess it shows up because the morphologizer has more labels. I'll add a commit for `Tagger`.

**Comment by adrianeboyd** [comment]
Most of the `morphologizer` code aside from the POS/FEATS label conversion is copied directly from `tagger`, so if one has a bug, the other probably does, too.

**Comment by danieldk** [comment]
There is a bit of low hanging fruit in training as well, but I'll make a separate PR for that (needs a bit more testing). It'll also not be as visible due to higher cost elsewhere.

**Comment by danieldk** [comment]
Seems like CI failed because it could not start a macOS runner?

**Comment by adrianeboyd** [comment]
Merge in `master` and try it again.

**Comment by svlandeg** [comment]
I think the CI just timed out. When this happens, it just needs a push on Azure "rerun failed pipelines".

**Pull request merged**
