### PR TITLE
Add option to disable pipes in EntityRuler

### PR DESCRIPTION
**Pull request by polm**
## Description

The EntityRuler uses reference to the calling `Language` internally to generate docs for matching. Depending on how the pipeline is configured, this can call pipes that aren't needed, resulting in unused work. This PR adds a `disable_pipes` option to the EntityRuler that allows specifying pipes that should be disabled when creating Docs internally. 

There are other ways this could be done. For example, we could try automatic inference of which pipes are needed, since pipes specify the attributes they set. But I think this approach is better, since we would want a manual override for any inference in any case.

Another thing to note is that pipes after the EntityRuler are disabled by default. Maybe it's enough if we make that more prominent in the documentation?

Currently this is just at a proposal stage, and these things still need doing:

- [ ] same feature in span ruler
- [ ] doc updates

### Types of change

enhancement

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by svlandeg — COMMENTED** [review]
It's a good point to raise - users are not necessarily realising the performance implication of moving the `entity_ruler` to a different place in the `pipeline`. I do think having to define the other pipes manually could be both error prone and tedious. Then again, automatically inferring might be error prone, too. One other alternative is to have the user define which pipeline components should run, but then dependencies (like on the `tok2vec`) might get forgotten.

Interested to hear what others think!

**Comment by rmitsch** [comment]
I'd be in favor of having the user disable pipes. I think it might be unexpected behavior if we automatically infer pipes only in this context. Using includes instead of excludes - that's what you meant, @svlandeg? - might be bothersome to implement for other reasons, if you remember the include/exclude/enable/disable PR (although maybe that's different here).

**Comment by adrianeboyd** [comment]
I mean more that if the user knows they need tags and they know they need `["tok2vec", "tagger"]` for this, then it's easier to use `source` to add the entity ruler to various pipelines (where you can't currently easily change config settings like this with `source`).

Then it doesn't matter whether there's `parser` or `ner` in the pipeline that they're adding the entity ruler to. It's not 100% foolproof in terms of which components might be providing tags (like whether you need `tok2vec` or where POS is coming from), but it's more flexible that specifying things to disable.

**Comment by polm** [comment]
I didn't know about the script workaround, which I agree almost makes this unnecessary, but it is a good point that won't help when loading a model. 

I think that specifying pipes to enable is much clearer than ones to disable. Since #10784 has been merged we can use the behavior there already too.

**Comment by svlandeg** [comment]
After internal discussion, we decided not to clutter up the config files with this setting, which we assume would only be relevant/useful for a limited number of users. 

Happy to reconsider at any point, and if we do decided we want this feature, we should make sure it works both for the `entity_ruler` as well as the `span_ruler`.

**Pull request closed without merging**
