### PR TITLE
Update universe.json

### PR DESCRIPTION
**Pull request by kevinlu1248**
## Description

Added my project `pyate` to Spacy Universe.

### Types of change

Updated universe.json.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by kevinlu1248** [comment]
> Hi @kevinlu1248, thanks for your pull request!  It looks like you haven't filled in the [spaCy Contributor Agreement](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#contributor-agreement) (SCA) yet. The agreement ensures that we can use your contribution across the project. Once you've filled in the template, put it in the `.github/contributors` directory and add it to this pull request. If your pull request targets a branch that's not `master`, for example `develop`, make sure to submit the Contributor Agreement to the `master` branch. Thanks a lot!
> 
> If you've already included the Contributor Agreement in your pull request above, you can ignore this message.

Fixed, sorry for misreading CONTRIBUTOR_AGREEMENT.md.

**Comment by adrianeboyd** [comment]
Thanks for this contribution! I think it might be nice to use the spacy pipeline example in this entry so the use with spacy is highlighted? (I noticed that there's a typo in the README with `add_pipeline` instead of `add_pipe`.)

**Comment by kevinlu1248** [comment]
@adrianeboyd Thanks for the input. Sorry about the typo and I have added the spacy pipeline code example.

**Comment by ines** [comment]
Thanks! 👍

**Pull request merged**
