### PR TITLE
Fix is_new_osx() in setup.py to identify macOS 11 and later correctly

### PR DESCRIPTION
**Pull request by ryandesign**
## Description
This PR fixes the `is_new_osx()` function in setup.py to identify macOS 11 and later correctly. It also fixes the function's doc string which misstated what the function does.

### Types of change
Bug fix

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
Thanks! There's a related PR on `develop` from some time back: PR #5376 

IIRC, at the time I submitted this to `develop` and not `master`, as there was some difference between Python 2 and 3, and support for Python 2 is dropped on the `develop` branch (which is work in progress for spaCy 3.0).

You're right that the docstring was wrong. And if we can make this function shorter, I'd be all for it!

**Comment by ryandesign** [comment]
I should have mentioned that I tested that the new function worked correctly on python 2.7.18 and 3.8.5. I can test other versions if you wish.

**Comment by ryandesign** [comment]
> There's a related PR on `develop` from some time back: PR #5376

I see... I didn't realize you had a develop branch. I just noticed a problem in your code, checked the default branch (master) to see if the problem still existed, which it did, so I submitted a fix. Hiding your latest code in a branch that is not the default branch makes it harder for people who aren't already familiar with your project to help you.

I also didn't realize that `distutils.util.get_platform()` returns the minimum platform for which the python binary was built (`MACOSX_DEPLOYMENT_TARGET`). (My python binary was built on my OS version so its deployment target is the same as my current OS version.) That distinction is probably important. For example, if you are building on 10.7 but with a deployment target of 10.6, you don't want to involve libc++ since libc++ didn't exist on 10.6. While I was rewriting the function it did occur to me that it should probably be looking at the value of `MACOSX_DEPLOYMENT_TARGET` being used to build spaCy, but it was my intention merely to fix the bug in the function and not change its behavior. I also don't know how to accomplish that as my experience with python is very limited.

Forcing the use of libc++ seems to be the only decision that's based on the result of `is_new_osx()`. Forcing the use of libc++ can be problematic. It's only ok if your use of C++ data structures is confined to your own software (i.e. you do not exchange C++ data structures with any library that you use or any other software that uses your software). So hopefully that is the case for spaCy.

Do you know why spaCy forces the use of libc++? It was done in 378ca4b46df9f88dfa359e994acab763b665d2f7 and the commit message says it fixes a problem but doesn't say what the problem was.

**Comment by svlandeg** [comment]
> Hiding your latest code in a branch that is not the default branch makes it harder for people who aren't already familiar with your project to help you.

We're not hiding anything - we're working on a new release of spaCy v.3 on the `develop` branch, while simultaneously still having made a few new release on v2.3.x, on the `master` branch.
I'm aware that you may not know this information - which is why I pointed it out in my reply.

**Comment by ryandesign** [comment]
> I want to let you know that I received this comment poorly.

I'm sorry, I should have worded it differently. I was frustrated that I had tried to provide a patch to your latest code but had been thwarted by the fact that your latest code was not where I expected to find it. I was upset I had wasted your time in reviewing a change that could not be applied to your latest code. I understand that there are surely valid reasons to develop code in another branch.

**Comment by honnibal** [comment]
@ryandesign Thanks, I understand the frustration and that it was coming from a good place 👍

**Comment by honnibal** [comment]
We should refactor the setup.py more generally and test on the different OSX versions we support. So I'm going to close this PR and revisit the issue later.

**Pull request closed without merging**
