### PR TITLE
Allow Doc.char_span to snap to token boundaries

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Add a `mode` option to allow `Doc.char_span` to snap to token boundaries. The `mode` options:

* `strict`: character offsets must match token boundaries (default, same as before)
* `inside`: all tokens completely within the character span
* `outside`: all tokens at least partially covered by the character span

Add a new helper function `token_by_char` that returns the token corresponding to a character position in the text. Update `token_by_start` and `token_by_end` to use `token_by_char` for more efficient searching.

### Types of change

Enhancement.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by honnibal** [comment]
This is a good idea, although I think we should think about better naming for the modes.

What about something like `strict`, `shrink` and `expand`?

**Comment by honnibal** [comment]
`contract` is definitely a better antonym for `expand`, but I worried it might be read as the noun, and then someone might wonder "What's the difference between `strict` and `contract`?"

**Comment by adrianeboyd** [comment]
`shrink` is just too weird, I wouldn't be able to guess what it means. `reduce`?

**Comment by honnibal** [comment]
Maybe `strict`, `smaller`, `larger`? Or possibly `exact`, `expand`, `contract`?

**Comment by adrianeboyd** [comment]
Does this get better if the setting is renamed to something like `snap_mode`? `snap_mode` = `exact`, `expand`, `contract`?

**Comment by honnibal** [comment]
I think tweaking the keyword name a little is good. I'm okay with any of the following:

* `snap_mode`: `exact`, `expand`, `contract`
* `if_misaligned`: `raise`, `expand`, `contract`?
* `tokens`: `exact`, `expand`, `contract`?
* `alignment`: `exact`, `expand`, `contract`?
* `borders`: `exact`, `expand`, `contract`?

So, feel free to pick one of the above (or make another suggestion).

**Comment by adrianeboyd** [comment]
Do you think `alignment_mode` is too long? `alignment_mode`: `exact`, `expand`, `contract`?

**Comment by honnibal** [comment]
I think it's okay to have a longer name for this. Let's do `alignment_mode`.

**Comment by itssimon** [comment]
@adrianeboyd is there a reason why this wasn't implemented for `Span.char_span()`? Would it make sense to keep these to functions consistent?

**Pull request merged**
