### PR TITLE
Adding examples for Czech languages

### PR DESCRIPTION
**Pull request by holubvl3**
In this pull request, I am adding file examples.py with examples for Czech language

### CODE REVIEW

**Comment by svlandeg** [comment]
Thanks for your contribution, this looks good!

The only thing that is a bit confusing, is that this PR contains the same commits as those from #5826. This makes comparison a bit difficult: if you go to the "file changed" tab at the top, it looks like you're again adding the `lex_attrs.py` file which is in fact already [present](https://github.com/explosion/spaCy/blob/master/spacy/lang/cs/lex_attrs.py) on the `master` branch after merging your last PR.

Going forward, it would be best if you could start from the most up-to-date `master` branch whenever you're creating a new PR. You can also [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) your git branch, or merge upstream/master into your local branch (see [syncing your fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)) to make sure we're only seeing the truly new commits for each PR.

**Comment by holubvl3** [comment]
Dear @svlandeg, I am sorry for inconvenience. I accidentaly use still the old branch. 

I made another branch, where just the new file - Create examples.py is added - https://github.com/explosion/spaCy/pull/5985

It´s possible to remove the PR? 

Thank you, and I am sorry again.

**Comment by svlandeg** [comment]
No worries at all! I'll close this PR and we'll merge the other one :-)

**Comment by holubvl3** [comment]
@svlandeg thank you!

**Pull request closed without merging**
