### PR TITLE
Update gold.align with pytokenizations

### PR DESCRIPTION
**Pull request by tamuhey**
From #4526 , #4554 
I created new `gold.align` in #4526 , but this algorithm assumes both toknizations add up to the same string and doesn't allow any noise (described in #4554).
Thus, I updated the `gold.align` based on [pytokenizations](https://github.com/tamuhey/tokenizations), which is I created for this purpose.
This library allows noisy tokenizations, and is very fast because it is implemented in Rust.

### Algorithm overview

1. Normalize tokens in the unicode normalization form "NFKD", then lowercase all characters.
2. Concatenate all tokens `tokens_a` and `tokens_b` to generate `ta` and `tb` respectively
3. Calculate shortest path on edit graph of `ta` and `tb` by [Myers' algorithm](http://www.xmailserver.org/diff2.pdf)
4. Get character mapping`c_ab` and `c_ba` from the edit graph
5. Get`al_ab` and `al_ba` from the character alignments `c_ab` and `c_ba`
6. Get `a2b`, `b2a`, `a2b_multi`, `b2a_multi`, and `cost` from `al_ab` and `al_ba`

### Types of change

an enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

I think the [doc](https://spacy.io/api/goldparse#align) should be modified.

### CODE REVIEW

**Comment by tamuhey** [comment]
Note:

- [pytokenizations](https://github.com/tamuhey/tokenizations) doesn't support Python2.7, so I defined `_USE_PYTOKENIZATIONS`  so that `gold.align` can work even if pytokenizations is not installed.

**Comment by tamuhey** [comment]
srsly build fails?

**Comment by honnibal** [comment]
I really appreciate the effort, but I think we'd be pretty reluctant to accept a new third-party dependency on a compiled module, especially written in a language we don't already maintain anything in.

The thing is, making sure wheels get built correctly as new versions come out, and making sure everything stays working across platforms as software stacks change, and ensuring everything stays working across both pip and conda, is a fairly big commitment. For our own libraries, we can take responsibility for this and it's mostly worth the effort for us, because we're doing this professionally. 

But we couldn't ask a third-party volunteer to do what we need. Even if you're happy to do it today, it's totally reasonable for your plans to change, and it shouldn't be your responsibility to make sure a bunch of companies get a smooth experience using some free code you wrote some time ago.

**Comment by adrianeboyd** [comment]
I also appreciate the effort, but I'd prefer to keep the constraint that the tokens have to match the text because it simplifies so many things.

**Comment by tamuhey** [comment]
Thanks, I got it. I think Cython is harder to maintain than Rust (debugging, memory management, and so on), but it can be also implemented in Cython.

I think an align function that can handle noisy tokens is necessary. Actually it is useful for [spacy-transformers](https://github.com/explosion/spacy-transformers/pull/123).

**Comment by honnibal** [comment]
@tamuhey Yes I agree that better handling of noisy alignments will be useful, especially in the `spacy-transformers`. I hope we can study your implementation later.

We've been working on a big update to the transformers support, which I hope we can show you soon :). If you want to test something early, feel free to email me at matt@explosion.ai 

In the meantime, I'll close this particular PR, because we want to avoid the Rust dependency, so we'll need to take a different approach.

**Pull request closed without merging**
