### PR TITLE
testing pydantic v1.10.0a1

### PR DESCRIPTION
**Pull request by samuelcolvin**
### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by adrianeboyd** [comment]
I think that `thinc` might be a better candidate for this test usage than `spacy`. Most of the interesting pydantic usage is in `thinc` anyway and `spacy` would require an updated pydantic version in `thinc` first, or there will be version conflicts.

It will get slightly more complicated in `thinc` at some point because we're moving the interesting config usage into a separate package (`confection`, to be released very soon), but if you start from the `v8.0.x` branch I think it should cover the cases you're interested in.

**Comment by samuelcolvin** [comment]
Thanks so much will do.

**Comment by adrianeboyd** [comment]
Wait, sorry, no not `v8.0.x` because that's not updated for pydantic v1.9. The current `master` (currently `01eb6b78`) should be okay, just be aware that it might change with `confection`.

**Comment by samuelcolvin** [comment]
will do, thanks.

**Pull request closed without merging**
