### PR TITLE
Reduce stored lexemes data, move feats to lookups

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Move non-derivable lexemes features (`norm / cluster / prob`) to `spacy-lookups-data` as lookups
  * Get/set `norm` in both lookups and `LexemeC`, serialize in lookups
  * Remove `cluster` and `prob` from `LexemesC`, get/set/serialize in lookups only
* Remove serialization of lexemes data as `vocab/lexemes.bin`
  * Remove `SerializedLexemeC`
  * Remove `Lexeme.to_bytes/from_bytes`
* Modify normalization exception loading:
  * Always create `Vocab.lookups` table `lexeme_norm` for normalization exceptions
  * Load base exceptions from `lang.norm_exceptions`, but load language-specific exceptions from lookups
  * Set `lex_attr_getter[NORM]` including new lookups table in `BaseDefaults.create_vocab()` and when deserializing `Vocab`
* Remove all cached lexemes when deserializing vocab to override existing normalizations with the new normalizations (as a replacement for the former step that replaced all lexemes data with the deserialized data)

### Types of change

Enhancement

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Sample lookups data for English here: https://github.com/adrianeboyd/spacy-lookups-data/tree/feature/lexeme-demo-data

**Comment by honnibal** [comment]
Looks good! Go ahead and merge it if it's safe.

**Comment by adrianeboyd** [comment]
Good! I think it needs to be coordinated with a release of `spacy-lookups-data` that moves all the features there, at least all the norm exceptions.

The remaining problem is that `spacy.blank()` (or similar) would then load all the prob and cluster data by default and this isn't great. I'm not sure how best to handle this?

**Comment by adrianeboyd** [comment]
The norm exceptions and their test have been moved to spacy-lookups-data.

How to handle prob/cluster is still outstanding, but I think once there's an updated release of spacy-lookups-data, this will be ready to go.

I've bumped the version for spacy-lookups-data, but since the CI doesn't include optional packages, I think the CI won't test those dependencies.

(Whoops, I realized I was thinking the dependency was the other way around. The spacy tests will be fine. The spacy-lookups-data tests will require an updated version of spacy to pass.)

**Pull request merged**
