### PR TITLE
Let --data-path be specified when running download.py scripts

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
## Description
Adds a `--data-path` (or `-d`) argument to the download.py scripts that lets the path to download to be specified.

## Motivation and Context
Makes downloading to a custom location easier; resolves https://github.com/explosion/spaCy/issues/637

## How Has This Been Tested?
Manually. After `pip install -e .`, I did a `git clean -xdf` to clean my local repo, then, in sequence:

- Checked that 

  ```
  import spacy
  spacy.load('en')('Hello, world')[0].pos_
  ```

  gives the empty string
- Ran `python3 -m spacy.en.download all -d ~/some_dir`
- Checked that `spacy.load('en')('Hello, world')[0].pos_` still gave the empty string but that `spacy.util.set_data_path('/home/mark/some_dir'); spacy.load('en')('Hello, world')[0].pos_` didn't.
- Ran `python3 -m spacy.en.download all`
- Checked that `spacy.load('en')('Hello, world')[0].pos_` no longer gave the empty string.
- Tried running `python3 -m spacy.en.download all` and `python3 -m spacy.en.download all -d ~/some_dir` again and confirmed that both exited early saying that the model was already installed.

## Types of changes

- [ ] Bug fix (non-breaking change fixing an issue)
- [x] New feature (non-breaking change adding functionality to spaCy)
- [ ] Breaking change (fix or feature causing change to spaCy's existing functionality)
- [ ] Documentation (Addition to documentation of spaCy)

## Checklist:

- [x] My code follows spaCy's code style. (*as far as I can tell - there's no actual style guide in CONTRIBUTING.md yet, so I just tried to imitate what was nearby)
- [x] My change requires a change to spaCy's documentation. (*ideally, anyway*)
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes. (*no tests for the downloader currently exist; any that we'd want to add would probably want to be CI-only, since they'll be extremely slow for anyone on a slow internet connection*)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
I'm gonna quickly add in docs, then this should be ready to merge.

**Comment by ExplodingCabbage** [comment]
Docs added, and looked at (both on the site on the local server and in the README on GitHub) to make sure the formatting came out right. Still not quite ready for merge - in the process of documenting ways to specify the path, I realised that passing a `path` to the `Language` constructor is broken (fixed by https://github.com/explosion/spaCy/pull/642/commits/b0a07c21a062c53b355efffbdc8b4f66f9c6842e) and I want to:

- [ ] Make sure it's properly fixed, and
- [ ] Make sure the tests still pass

Once that's done, I'll hand this over to y'all.

**Comment by ExplodingCabbage** [comment]
This is ready for review, I think.

**Comment by ines** [comment]
Agree – looks great and thanks for adding the sections to the docs and readme! 👍 
Feel free to add yourself to the [CONTRIBUTORS.md](https://github.com/explosion/spaCy/blob/master/CONTRIBUTORS.md), btw.

**Comment by ExplodingCabbage** [comment]
> Feel free to add yourself to the CONTRIBUTORS.md, btw.

I'll leave it to you to do so or not as you see fit - I feel like I probably shouldn't be making the decision about whether I get added or not. :)

**Comment by ines** [comment]
@ExplodingCabbage Sure, we'd be happy to add you! 😃 

Just saw that your GitHub profile only shows your user name – which name would you like me to use for the CONTRIBUTORS.md? We usually list contributors as "Full name, username", but an alias instead of the full name would be fine, too.

**Comment by ExplodingCabbage** [comment]
@ines My real name is "Mark Amery". :)

**Pull request merged**
