### PR TITLE
set split_mode from meta.json

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**
Set split_mode setting from meta.json

## Description

Apply "split_mode" entry under "tokenizer" in meta.json to set SudachiPy mode from model side to ensure the backward version compatibility. I added an argument to create_tokenizer() to receive the split mode setting described in meta.json

I ran `spacy.test.lang.ja`.
And I put "split_mode": "A" or "B" or "C" in "tokenizer" section in meta.json and tested this setting by running `spacy evaluate` with this modified model.
Also empty "tokenizer" entry and no "tokenizer" entry are tested.

(I submitted hiroshi-matsuda-rit.md in another PR. https://github.com/explosion/spaCy/pull/5560/files)

### Types of change

- improve model version compatibility

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by hiroshi-matsuda-rit** [comment]
Please use these examples to test. @adrianeboyd 
https://github.com/WorksApplications/Sudachi#the-modes-of-splitting

**Comment by adrianeboyd** [comment]
As a heads up, I'm going to push directly to your branch here to add the serialization details and tests. I've modified the config setup a bit to look more like Chinese, mainly to make things more uniform on our end.

After merging the alignment PR, I'll probably also need to resolve a few conflicts in this PR.

**Comment by adrianeboyd** [comment]
Ah, wait, it's not enabled here, let me see...

**Comment by hiroshi-matsuda-rit** [comment]
What's going on? @adrianeboyd 
This is my test result.
```
{
  "lang":"ja",
  ...
  "tokenizer": {
    "split_mode": "C"
  },
  ...
}
```
```
nlp = spacy.load('models/ja_gsd-2.3.0_C/model-best')
for t in nlp('選挙管理委員会'):
    print(t.orth_)
選挙管理委員会

nlp = spacy.load('models/ja_gsd-2.3.0_A/model-best')
for t in nlp('選挙管理委員会'):
    print(t.orth_)

選挙
管理
委員
会
```

**Comment by adrianeboyd** [comment]
If you're testing #5562 (and not this PR), I modified the configuration of the settings a bit. It would look like this:

```
nlp = Japanese(meta={"tokenizer": {"config": {"split_mode": "B"}}})
```

See the tests in `test_serialize` and `test_tokenizer` for examples.

Let me close this and let's move the discussion to #5562.

**Pull request closed without merging**
