### PR TITLE
Rule-based lemmatization in Spanish

### PR DESCRIPTION
**Pull request by pablodms**
Replaces lookup table based lemmatization in Spanish to rule-based lemmatization using Wiktionary ES  latest dump.

## Description
Parsing process is explained in the following [Jupyter Notebook](https://github.com/pablodms/wictionary_es_dump/blob/master/Dump%20lemmas%20from%20Wicktionary%20ES.ipynb). This notebook parses a downloaded dump file from [Wiktionary ES](https://dumps.wikimedia.org/eswiktionary/latest/), extracts metadata for each term in Spanish language and finally writes "lemma_exc.json" which contains mappings from variations to root terms for adjectives, adverbs, nouns, verbs, pronouns and determinants .

Then, previous lemma_exc.json and simple lemma_index.json and lemma_rules.json have been added to spacy/lang/es/lemmatizer.  _\_\_init\_\_.py_ file in spacy/lang/es has been modified to load these new files.

Also, I have modified lemmatizer in spacy to add support to DET and ADV Pos Tags, needed for a correct lemmatization for determinants and adverbs in Spanish.

This way issue #2668 for Spanish lang should have been addressed.

Changes have been tested against sentences written in #2710 producing more coherent lemmatization.

### Types of change
Enhacement

## Checklist

- [X] I have submitted the spaCy Contributor Agreement.
- [ ] I ran the tests, and all new and existing tests passed. -> I got 59 fails both in master and modified branch.
- [X] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by pablodms** [comment]
I have misspelled "pron" tag as "pronoun", latest commit fixes this issue.

**Comment by honnibal** [comment]
@pablodms Sucks :(. You can always make a package that people can use as an extension?

**Comment by sontek** [comment]
Has there been any progress towards splitting this out into its own extension?  I'm have a significant amount of issues with Spanish and this seems like it might help?  Here are the problems I'm having:

#4341
#4340
#4255
#4254
#4253

But it seems like a lot of them would address both #3052 and your original idea for fixing #2668

**Comment by sontek** [comment]
Also, @pablodms Looks like you had some good stuff in here outside of the wiktionary stuff that might be worth merging?  Do you want to send a separate PR for some of your rules and the implementation of DET and ADV?

**Comment by pablodms** [comment]
Hello @honnibal and @sontek,

Sorry for the delay,

These days I have been thinking about how to integrate wiktionary data without breaking the license terms.  I believe that if I only put the code to download, parse and finally generate lemmatizer files in the spacy project, I will not be breaking license since **spacy will not be distributing code based in Wiktionary data**, only code that is able to download this data and use it only if requested by user. The final user will then be able to locally configure and use the Spanish lemmatizer using Wiktionary data. 

Some issues related to this idea are: time (1-2 minutes) and disk space (around 1GB) taken  to parse dump file, and local privileges to download, create and copy needed files for lemmatizer.

What do you think @honnibal? Should I make a new pull request following this strategy?

**Comment by sontek** [comment]
@honnibal Any chance we can consider re-opening this PR and getting it merged?   I just noticed that spacy already relies on this same dataset for other languages:

https://github.com/explosion/spaCy/blob/e0cf4796a505bd26e8fcb95d23b89fd7eca3be0a/spacy/lang/el/get_pos_from_wiktionary.py#L5

https://github.com/explosion/spaCy/blob/146dc2766a069c8fe9e91c801f9695c2e262f742/spacy/lang/sv/morph_rules.py#L7

**Comment by versae** [comment]
+1 to merge this!

I've been running into similar issues and would love to have this merged, or at least living in its own package. Moreover, if GPLv2 or LGPL-LR were compatible, [UDLexicons 0.2](http://pauillac.inria.fr/~sagot/index.html#udlexicons) could be used, which include a couple of Spanish lexicons: UDLex_Spanish-Apertium (324925 words, GNU GPL v2) and UDLex_Spanish-Leffe (843426 words, LGPL-LR).

On the other hand, our project [spacy-affixes](https://github.com/linhd-postdata/spacy-affixes/) (a spaCy Pipeline to split clitics) uses Freeling rules and delegates the download of the data to the user so the license is honoured.

**Comment by pablodms** [comment]
Hello @versae,

Since I think this request has been abandoned, I will try to develop a separate package following the idea of your project: implement lemmatizer as a spaCy pipeline stage. I will tell if I get any progress.

Thanks for your suggestions.

**Comment by versae** [comment]
That's great news, @pablodms. A new pipeline would come in handy and if you need a hand with that just let me know. We could join forces!

**Comment by pablodms** [comment]
I have developed a basic version and uploaded it to pip, @versae. In the [repository](https://github.com/pablodms/spacy-spanish-lemmatizer) there are simple instructions to deploy the package. I have no experience in developing Python packages, in fact, this is my first attempt, so any help would be greatly appreciated. Your proyect has been a great inspiration, by the way.

In addition, downloading (~65MB compressed file) and parsing (~900MB decompressed file) dump files is currently **SLOW**, so it can take several minutes.

**Comment by versae** [comment]
That's awesome, @pablodms! Thanks for releasing it in such a short time :) Maybe in the future we could add the lemmas from UDLexicons too. I have a parser of the format and would not be a lot of work.

**Comment by pablodms** [comment]
I can, @versae, add you as a contributor to the [spanish-lemmatizer](https://github.com/pablodms/spacy-spanish-lemmatizer) project so you can include your parser and your experience if you wish.

**Pull request closed without merging**
