### PR TITLE
DOC "OP" key in token spec

### LINKED ISSUE #1104: Unclear in documentation how to use "quantifiers"
See here https://spacy.io/docs/usage/rule-based-matching#quantifiers

Related doc line:
https://github.com/explosion/spacy/blob/master/website/docs/usage/rule-based-matching.jade#L60

### PR DESCRIPTION
**Pull request by jnothman**
## Description

Fixes #1104 rather than leaving it broken which seemed to be the executive decision.

## Types of changes
- [ ] **Bug fix** (non-breaking change fixing an issue)
- [ ] **New feature** (non-breaking change adding functionality to spaCy)
- [ ] **Breaking change** (fix or feature causing change to spaCy's existing functionality)
- [x] **Documentation** (addition to documentation of spaCy)

## Checklist:
- [x] My change requires a change to spaCy's documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jnothman** [comment]
I hereby release all rights to this contribution. It is now in the public
domain. Do with it as you wish.

**Comment by honnibal** [comment]
@jnothman Thanks for the fix.

To help you make sense of the current state: we've been putting our energy into fixing the docs for v2, and haven't been spending much time backporting fixes into the v1 docs. The same is true for bugfixes. This sucks temporarily, but is best in the long term.

v2 is now feature complete. We'll push a release candidate as soon as we fix the last 3 open bugs, and port a couple of pull requests over.

After the v2 release candidate, we'll be releasing a v1.10 with the current patches on master and some backported bug fixes. If we can add some forwards-compatibility helpers to assist migration, that's also great too. I'm hoping the community can continue helping with this.

**Comment by jnothman** [comment]
I had not realised the extent of divergence of API and docs in v2.0. This is greatly exacerbated by the fact that it's very hard in the spacy.io docs to tell which version you're looking at and how to get to another. I strongly recommend fixing that.

**Comment by ines** [comment]
@jnothman Sorry this hasn't been clear – we're definitely looking forward to publishing the release candidate and stable v2.0, and switching the official docs to the new version. The current situation is pretty exceptional in the sense that we're juggling two major versions in parallel, due to the significant changes in v2.0.

At the moment, there are only two versions of the docs:
* [spacy.io](https://spacy.io) – the docs for the current 1.x
* [alpha.spacy.io](https://alpha.spacy.io) – the new alpha docs for v2.x with a new and improved design, new structure and almost entirely re-written content (still experimental in some places, still subject to change and reflecting the intended state of the library, not always the current implementation – although we're about 90% there now).

Once v2.0 is released officially, the v1.x docs will probably be available as legacy.spacy.io for a while, and linked from the new docs and landing page. The new docs layout also allows labelling features or methods as "new in vX" to make individual updates more visible in the future.

The reason we're doing it this way is to avoid the search engine problems that come with including the full, versioned history of the docs on the website. It's pretty much impossible to prevent a user from accidentally ending up on an outdated page. Similarly, when we're linking to a usage guide – e.g. on the issue tracker or StackOverflow – we generally want it to point to the latest version. If a new user comes across the discussion months later, they should find the correct documentation for the latest version – not the version at the time the link was posted.

To still allow users to access the documentation at the time of an individual spaCy release, we're shipping the source of the website and docs as part of the spaCy repository. This way, a user can always run the site locally from any tag, and access the state of the documentation at the time of the release.

**Pull request merged**
