### PR TITLE
Update br tags

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

I think the intention in displacy was `<br/>`, but maybe now `<br>` would be better (says the w3c markup validator anyway)?

### Types of change

Bug fix?

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by rmitsch** [comment]
Does this fix a bug? I just wouldn't want to assume the closing tag is an opening tag. `<br>` should be sufficient now AFAIK, yes (not an expert though).

**Comment by adrianeboyd** [comment]
I think all browsers probably render `<br>`, `</br>`, and `<br/>` the same so it's not exactly a bug? It's been like this for ages. I'd noticed a few times in the past when inspecting the rendering but never worried about it beyond that. But I don't think that `</br>` has ever been an actual valid tag?

**Comment by rmitsch** [comment]
Ah right, it's just line break.

**Review by rmitsch — APPROVED** [review]

**Review by svlandeg — APPROVED** [review]
If the w3c markup validator suggests `<br>` I would yet change it into that, but I suspect that it won't make a practical difference either way.

**Pull request merged**
