### PR TITLE
Fix passing of component configuration

### PR DESCRIPTION
**Pull request by svlandeg**
Fixes Issue #5137 + unit test

## Description
As described in the [documentation](https://spacy.io/usage/saving-loading#advanced-cfg), 
```
nlp = spacy.load("en_core_snek_sm", snek_style="cute")
```
should pass on the custom configuration (`snek_style`) all the way down to the `init` `**cfg` of a custom component.

This was not actually happening though. Added a quick fix by putting `config.update(overrides)` to pass that `config` on to `create_pipe`.

### Types of change
bug fix

## Checklist
- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
I'm a little worried that this might cause problem if the overriding isn't component-specific? What if I have a setting with the same name in two components?

**Comment by svlandeg** [comment]
The way it's written in the documentation, does assume the additional configuration is non-specific. The alternative would get kind of clunky I think ?

**Comment by adrianeboyd** [comment]
Okay, it's probably used rarely enough that it's not a big deal either way.

**Comment by honnibal** [comment]
This stuff was really messy in v2. It should be a bit more consistent in v3, but yeah there have definitely been bugs on this.

**Pull request merged**
