### PR TITLE
Update quickstart vectors recommendations

### LINKED ISSUE #6260: Base config includes reference to unavailable en_vectors_web_lg (spacy-nightly)
## How to reproduce the behaviour
With spacy-nightly installed:

```
python -m spacy init config base.cfg --optimize=accuracy --cpu
python -m spacy init fill-config base.cfg config.cfg
python -m  spacy download en_vectors_web_lg   
```

returns:

```
Collecting en_vectors_web_lg==3.0.0a0
  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-3.0.0a0/en_vectors_web_lg-3.0.0a0.tar.gz#egg=en_vectors_web_lg==3.0.0a0
ERROR: Could not install requirement en_vectors_web_lg==3.0.0a0 from https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-3.0.0a0/en_vectors_web_lg-3.0.0a0.tar.gz#egg=en_vectors_web_lg==3.0.0a0 because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-3.0.0a0/en_vectors_web_lg-3.0.0a0.tar.gz for URL https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-3.0.0a0/en_vectors_web_lg-3.0.0a0.tar.gz#egg=en_vectors_web_lg==3.0.0a0
```

in `config.cfg` the line is:

```
[initialize]
vectors = "en_vectors_web_lg"
```

Assuming this will be fixed once 3.0 is final, but wanted to highlight for others who might be using nightly and expecting the config to work out of the box.

## Your Environment
- **spaCy version:** 3.0.0rc1
- **Platform:** macOS-10.14.6-x86_64-i386-64bit
- **Python version:** 3.8.6
- **Pipelines:** en_core_web_lg (3.0.0a0), en_core_web_trf (3.0.0a0)

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

* Switch from `en_vectors_web_lg` to `en_core_web_lg`
* Add vectors recommendations for all core models
* Sort list

Fixes #6260.

### Types of change

Bug fix.

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
It looks like the docs also included some outdated references, e.g. to `https://nightly.spacy.io/models/en-starters` (if you search on `_vectors_web`), perhaps update those as well?

**Comment by adrianeboyd** [comment]
Hmm, do we want to keep publishing `en_vectors_web_lg` at all? I'm not sure it provides much value over `en_core_web_lg` for most people and I'd rather not maintain it.

I updated the v2.1 model for v2.3 without really touching the internals (there are several missing strings) and if we did publish a new version, I would want to redo it and remove those, so it wouldn't be 100% identical.

**Comment by svlandeg** [comment]
My point was, indeed assuming we won't be publishing them anymore, we also need to remove their references from the docs ;-)

**Comment by adrianeboyd** [comment]
I think we can separate this decision from this PR, since none of the docs mentions look relevant to the quickstart recommendations?

**Comment by ines** [comment]
> Hmm, do we want to keep publishing en_vectors_web_lg at all? 

I was talking about this with @honnibal the other day and I think with the new project templates etc., we want to guide people towards using `init vectors` (or one of the core models) rather than distributing a bunch of these vectors-only packages.

> It looks like the docs also include some outdated references, e.g. to https://nightly.spacy.io/models/en-starters (if you search on _vectors_web), perhaps update those as well?

Ah, I'll fix this. I just removed the starters from the sidebar but I forgot the actual pages and references.

**Comment by adamkgoldfarb** [comment]
For those who have been using vectors to jumpstart blank models as one recommended approach to training in Prodigy, is the new recommended approach to use en_core_web_lg as a drop-in replacement? If so, would one have to extract the vectors from the full model, or will one just use the same commands as before? 

And if this will all be resolved/made clear once Prodigy is brought up to speed with v3 then ignore this-- just trying to plan out the steps and allocate resources for training in the future!

As I understand from the docs we can also head to e.g. [GloVe](https://nlp.stanford.edu/projects/glove/) and `init vectors` on one of the downloaded vectors and use the resulting vectors as we have been, so just confirming that's the case as well.

Thanks very much for all this great stuff!

**Pull request merged**
