### PR TITLE
Add support for Universal Dependencies v2.0

### PR DESCRIPTION
**Pull request by rominf**
## Description
I'm working on Russian language support. This commit is a prerequisite (Russian UD corpus uses UD v2.0).

## Types of changes
I looked at UD v2.0 documentation and added some symbols. To keep old code working, I didn't remove old symbols, even if it was required by new standard.

## Checklist:
- [ ] My change requires a change to spaCy's documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks!

There's currently a bad design mistake with these attributes: The `vocab` object adds these symbol names at the start of the `StringStore`. This means that adding these attributes changes the offset of the string-to-integer table, breaking compatibility with the pre-trained models.

I therefore have to hold off on merging this until I get the models retrained. The plan is to change the vocab code so that there's a fixed-size region of indices reserved for these special symbols --- say, 1000 or so. This way, we won't have to offset the vocabulary words when we map these symbols, and the same problem won't reoccur.

**Comment by rominf** [comment]
@honnibal 
OK, understand. Should I use this commit in my `russian`-support branch (I think, yes)?

**Comment by honnibal** [comment]
Yes.

**Comment by honnibal** [comment]
I've got this merged on the develop branch, and have the models training. I've been doing some experiments with L1 regularization, which should finally produce small models for testing. I hope to have something uploaded on this today.

**Pull request merged**
