### PR TITLE
PR for testing Thinc 703

### PR DESCRIPTION
**Pull request by svlandeg**
## Description
dummy PR for testing purposes only - should not be merged

PR to test the CI with the Thinc branch for https://github.com/explosion/thinc/pull/703

### CODE REVIEW

**Comment by svlandeg** [comment]
@explosion-bot please test_slow --thinc-branch develop

**Comment by svlandeg** [comment]
@explosion-bot please test_slow --thinc-branch refs/pull/703/head

**Comment by svlandeg** [comment]
@explosion-bot please test_slow

**Comment by svlandeg** [comment]
The slow test suite was (unrelatedly) broken. This should just be green with the default thinc install.

**Comment by shadeMe** [comment]
@explosion-bot please test_slow --thinc-branch refs/pull/703/head

**Comment by shadeMe** [comment]
PSA: Currently testing explosion-bot with this PR. In case you see a lot of related activity, keep calm and continue.

**Comment by shadeMe** [comment]
> _⏳ Triggering 'Slow Tests' for 'spaCy' on Buildkite..._

**Comment by shadeMe** [comment]
@explosion-bot please test_slow --thinc-branch refs/pull/703/head

**Comment by svlandeg** [comment]
@explosion-bot please test_slow --thinc-branch refs/pull/703/head

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 💬 Help for command `test_slow`

```
Usage: @explosion-bot please test_slow [OPTIONS]

  Trigger a build against the spaCy/thinc Slow Test Suite BuildKite pipeline

Options:
  --thinc_branch TEXT  Build thinc from this branch for the test.
  --spacy_branch TEXT  Build spaCy from this branch for the test. Can only be
                       used in the spaCy Transformers repo.

  --run_on TEXT        Execute this command on a different repo but with the
                       changes in the current PR. Valid source -> target repos:
                       spaCy -> spaCy Transformers, thinc -> spaCy, spaCy
                       Transformers

  --help               Show this message and exit.
```

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --spacy-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_slow [OPTIONS]
Try '@explosion-bot please test_slow --help' for help.

Error: no such option: --thinc-branch

**Comment by shadeMe** [comment]
> _The '--spacy-branch' option can only be used in the following repos: ['spacy-transformers']_

**Comment by shadeMe** [comment]
> _This repository (spacy) is not supported by me at the moment!_

**Comment by shadeMe** [comment]
> _The '--run-on' option can only be used in/with the following repos (source: target): {'spaCy': ['spacy-transformers'], 'thinc': ['spaCy', 'spacy-transformers']}_

**Comment by shadeMe** [comment]
> _No 'Slow Tests' build pipeline found for the repo 'spacy-transformers'!_

**Comment by shadeMe** [comment]
> _No 'Slow Tests' build pipeline found for the repo 'spacy-transformers'!_

**Comment by shadeMe** [comment]
> _The '--spacy-branch' option can only be used in the following repos: ['spacy-transformers']_

**Comment by shadeMe** [comment]
> _❌ The '--spacy-branch' option can only be used in the following repos: ['spacy-transformers']_

**Comment by shadeMe** [comment]
### 🚨 Errors

❌ The '--spacy-branch' option can only be used in the following repos: ['spacy-transformers']

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_gpu [OPTIONS]
Try '@explosion-bot please test_gpu --help' for help.

Error: no such option: --spsacy-branch

**Comment by shadeMe** [comment]
### 🚨 Errors

Usage: @explosion-bot please test_gpu [OPTIONS]
Try '@explosion-bot please test_gpu --help' for help.

Error: no such option: --spsacy-branch

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
### 🚨 Errors


Aborted!

**Comment by shadeMe** [comment]
### 🚨 Errors

The '--run-on-branch' option must/can only be used together with the '--run-on' option

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
### 🚨 Errors

`current_pr` can only be used in PRs of the corresponding repo

**Comment by shadeMe** [comment]
### 🚨 Errors

```
Traceback (most recent call last):
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/click/testing.py", line 329, in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/madeesh/miniconda3/envs/dev/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/madeesh/dev/explosion-bot/explosionbot/github_commands/test.py", line 225, in test_gpu
    test_command(params)
  File "/home/madeesh/dev/explosion-bot/explosionbot/github_commands/test.py", line 182, in test_command
    pipeline, bk_queue = TEST_PIPELINES[(params.repo, params.test_suite)]
AttributeError: 'Repo' object has no attribute 'repo'
```

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
> _⏳ Triggering 'GPU Tests' for 'spacy-transformers' on Buildkite..._

**Comment by shadeMe** [comment]
### 🚨 Errors

This repository (spacy-transformsers) is not supported by me at the moment!

**Pull request closed without merging**
