### PR TITLE
Restructure Sentencizer to follow Pipe API

### PR DESCRIPTION
**Pull request by adrianeboyd**
## Description

Restructure Sentencizer to follow Pipe API so that it can be scored with `nlp.evaluate()`.

### Types of change

Enhancement?

## Checklist

- [x] I have submitted the spaCy Contributor Agreement.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
This PR is based on #4632, which should be merged first.

**Comment by adrianeboyd** [comment]
This should probably be done against master instead (I just did it this way so I could run direct evaluations with the proposed `SentTagger`) and after looking at the parser more, I also think that it shouldn't set `sent_start` to `-1` anywhere, just like the parser, but that should be a separate issue/PR, too. (Or is there a reason it sets all tokens? Is there a reason to want to prevent later components from adding more boundaries?)

**Comment by honnibal** [comment]
@adrianeboyd Setting 1 vs -1 is a tricky question. I could imagine not wanting the parser to split sentences the sentencizer hasn't split. It should probably be a setting?

Merging this onto master seems like a fine choice.

**Comment by adrianeboyd** [comment]
It could be a setting, or maybe having an extra pipeline component would be more flexible? The other components only set `1` and you add something like `finalize_sentences` at a particular point if you want the rest to become `-1`?

**Comment by adrianeboyd** [comment]
Replaced by #4721.

**Pull request closed without merging**
