### PR TITLE
Add DeepPavlov into SpaCy Universe

### PR DESCRIPTION
**Pull request by moryshka**
## Description
The DeepPavlov framework was added to the SpaCy universe json file.

### Types of change
change to universe

## Checklist

### CODE REVIEW

**Comment by moryshka** [comment]
> Thanks, this looks interesting! One small request: Maybe it could be nice to add a note to the description about how spaCy is being used in the project?
> 
> When I took a quick look at the GitHub, I first checked the README and requirements to see what it was using under the hood, and didn't find spaCy anywhere. I did find [in the code](https://github.com/deepmipt/DeepPavlov/search?p=1&q=spacy&type=&utf8=%E2%9C%93), though, so I guess it uses spaCy as an option for tokenization and preprocessing?

Thank you for your comment, I've added how DeepPavlov uses SpaCy in the description section.

**Comment by moryshka** [comment]
> Hi @moryshka, thanks for your pull request! 👍 It looks like you haven't filled in the [spaCy Contributor Agreement](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#contributor-agreement) (SCA) yet. The agrement ensures that we can use your contribution across the project. Once you've filled in the template, put it in the `.github/contributors` directory and add it to this pull request. If your pull request targets a branch that's not `master`, for example `develop`, make sure to submit the Contributor Agreement to the `master` branch. Thanks a lot!
> 
> If you've already included the Contributor Agreement in your pull request above, you can ignore this message.

I appreciate your comment, I've added the agreement into the contribution directory.

**Comment by ines** [comment]
@moryshka Thanks! 👍

> Thank you for your comment, I've added how DeepPavlov uses SpaCy in the description section.

Do you have a link? I can't find it – or maybe I'm looking in the wrong place?

**Comment by honnibal** [comment]
This looks like a really cool project, but with the universe growing quickly, we probably want to focus on projects where people can see something about the usage of spaCy, or get a sense of what problems spaCy is solving. I think if spaCy's just being used internally for tokenization, it's much less interesting from a spaCy perspective.

We definitely appreciate the thought, and again, it looks like a really cool project. But I think we probably want to make sure the universe stays a bit more spaCy-centric.

**Pull request closed without merging**
